### ISSUE TITLE
Animation jittery even though fps stays at 60fps

### ISSUE THREAD

**Issue by himanshu266** [software-mansion/react-native-reanimated#1371]
## Description
Scrollview scroll with modifying the height of the header is super jittery. The only device it works on properly is iPad Pro. All iPhones it does not work well. Test devices iPhone 11 Pro, iPhone 6 and iPad Pro. Also it appears to just be on momentum scroll. (The event throttle is 1).

### Screenshots

![video](https://user-images.githubusercontent.com/442169/96917937-816cff80-1477-11eb-949b-3a71bef6d5dd.gif)

## Steps To Reproduce
See code below.

### Expected behavior
Smooth height animation.

### Actual behavior
Jittery animation.

## Snack or minimal code example
```
import React from 'react';
import { View, StyleSheet } from 'react-native';
import Animated, { interpolate, useSharedValue, useAnimatedStyle, useAnimatedScrollHandler, Extrapolate } from 'react-native-reanimated';

function ScrollExample() {
  const y = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler((event) => {
    y.value = event.contentOffset.y;
  });

  const stylez = useAnimatedStyle(() => {
    const height = interpolate(y.value, [-100, 0, 200], [500, 400, 100], Extrapolate.CLAMP)
    return {
      height: height,
      // zIndex: height > 100 ? 0 : 1,
    };
  });

  console.log('render');

  return (
    <View style={{flex: 1, backgroundColor: '#f1f2f3'}}>
      <Animated.View style={[{backgroundColor: '#fab', ...StyleSheet.absoluteFill, bottom: null }, stylez]} />
      <Animated.ScrollView
        contentContainerStyle={{paddingTop: 300}}
        onScroll={scrollHandler}
        scrollEventThrottle={1}>
        <View style={{height: 200, margin: 20, marginBottom: 0, backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ccc', borderRadius: 8}} />
        <View style={{height: 200, margin: 20, marginBottom: 0, backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ccc', borderRadius: 8}} />
        <View style={{height: 200, margin: 20, marginBottom: 0, backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ccc', borderRadius: 8}} />
        <View style={{height: 200, margin: 20, marginBottom: 0, backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ccc', borderRadius: 8}} />
        <View style={{height: 200, margin: 20, marginBottom: 0, backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ccc', borderRadius: 8}} />
        <View style={{height: 200, margin: 20, marginBottom: 0, backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ccc', borderRadius: 8}} />
      </Animated.ScrollView>
    </View>
  );
}

export default ScrollExample
```

## Package versions

- React: ~16.13.0
- React Native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz (.63)
- React Native Reanimated: 2.0.0-alpha.6.1
- NodeJS: 12.19.0

**Comment by jakub-gonet** [comment]
Height is a layout property, so animating it requires layout recalculation. Have you tried using transforms to do achieve that?

**Comment by himanshu266** [comment]
Yes, I've tried that. It's the same issue. This works fine in Reanimated 1 btw, no issues. Also, works on iPad no issues.

**Comment by himanshu266** [comment]
Also, it works fine if I keep my finger on the screen. It's the momentum when it glitches.

**Comment by terrysahaidak** [comment]
Can you try running that header change heigh animation not based on scroll position, but iterpolate based on shared value with an animation?

If you didn't see the lag the it was the problem with a few frames delay when we release the gesture and run animation.

On iPad pro it's not visible since it runs on 120fps and those 3 frame aren't that visible.

**Comment by himanshu266** [comment]
@terrysahaidak So it is smoother with:
```
return {
    height: withTiming(y.value < 100 ? 400 : 100)
}
```
compared to:
```
return {
    height: interpolate(y.value, [-100, 0, 200], [500, 400, 100], Extrapolate.CLAMP)
}
```

This experience isn't ideal, so I don't know how to deal with this issue. Is there a possible fix? Worked fine with reanimated-1 and also works fine when I'm dragging it, the momentum is the issue.

@wcandillon Have you experienced this with reanimated-2?

**Comment by terrysahaidak** [comment]
This is no workaround, just checking if this the same issue @karol-bisztyga, @Szymon20000 and me are currently working on. And seems like it is.

The problem is in when we run the animation. Basically, if you replay your animation frame by frame you can notice 2 frames delay after you release the gesture and run the spring.

**Comment by himanshu266** [comment]
Yep, I see the delay. The same thing happens with translate or scale or any other animation. The `useAnimatedGestureHandler` seems to work fine though. Ok, thanks for confirming. I will keep an eye out for updates. Thanks for all the hard work, reanimated2 is great.

**Comment by vcapretz** [comment]
hey, I have a similar (maybe even the same issue), not sure if it helps but I do see the glitch as well, running alpha v7 with Expo 39.0.3. I have a `createAnimatedComponent(FlatList)` which receives a `onScroll`:

```js
const onScroll = useAnimatedScrollHandler({
    onScroll: (event) => {
      scrollY.value = event.contentOffset.y;
    },
  });
``` 

which I use to translateY in an `Animated.View` like so: 
```js
const style = useAnimatedStyle(() => {
    const y = interpolate(
      scrollY.value,
      [0, headerHeight],
      [0, -headerHeight],
      Extrapolate.CLAMP
    );

    return {
      transform: [{ translateY: y }],
    };
}, [headerHeight]);
```


```jsx
<Animated.View
    style={[
    {
        top: 0,
        zIndex: 1,
        position: "absolute",
        width: "100%",
    },
    style,
    ]}
>
```

will keep an eye in future alpha updates too, great work btw, I am really enjoying using v2 much more than v1 😄

**Comment by terrysahaidak** [comment]
Hi @vcapretz this issue is resolved in alpha.7, but since you use expo the only available release for you is alpha.6.1. Make sure to use this exact one to avoid some unexpected bugs.

**Comment by ciawalsh** [comment]
@vcapretz - I'm noticing this is an issue mostly with using `interpolate` within `createAnimatedComponent(FlatList)` vs using within a standalone `Animated.ScrollView` - The scrollview is 60fps, whereas the flatlist looks very janky.

**Comment by vcapretz** [comment]
@ciawalsh do you think that I should explore an alternative where I use the scroll view instead? I know it might not be as performant as the FlatList but I never know how many components are too much to be rendered at once in a scroll view 🤔

**Comment by jakub-gonet** [comment]
This should be resolved.

**Comment by olosegres** [comment]
@jakub-gonet 
Hi, I do not understand, why you closed this issue before it become resolved? :)
Bug still exist.

**Comment by arthurgeron-work** [comment]
I'm on 2.5.0, and if a element inside my scroll is animating with interpolation while the user is scrolling the scroll jitters..
