### ISSUE TITLE
alpha8 JS thread functions called without `runOnJS()` crash ungracefully

### ISSUE THREAD

**Issue by wcandillon** [software-mansion/react-native-reanimated#1393]
Functions that now require to use runOnJS() causes the app to crash if runOnJS() is not used. However it crashes quite abruptly.
This is on Android.

**Comment by drewandre** [comment]
Some documentation or at least mentioning of this as a breaking api change would have been nice, but otherwise alpha 8 has been an amazing release. Thank you!

I've also seen the android-specific issue described here. I just wanted to comment below how I ended up refactoring my main JS thread function calls in case anyone else has `runOnJS` issues:

alpha-7:
```
const tapGestureHandler = useAnimatedGestureHandler({
  onActive: (evt, ctx) => {
    onPress() // onPress comes from props
  }
  ...
```
alpha-8:
```
import { runOnJS } from 'react-native-reanimated'

const tapGestureHandler = useAnimatedGestureHandler({
  onActive: (evt, ctx) => {
    runOnJS(onPress)()
  }
  ...
```

**Comment by terrysahaidak** [comment]
If you have few assigns of some shared values in a row and wanna make sure it's synchronous you should use rubOnUI, because real assign to the shared value is asynchronous

**Comment by drewandre** [comment]
Otherwise in a normal scenario you shouldn’t have to use runOnUI, right? If I’m just seeing an animated value on the main react-native JS thread? Thanks @terrysahaidak

**Comment by terrysahaidak** [comment]
> Otherwise in a normal scenario you shouldn’t have to use runOnUI, right? If I’m just seeing an animated value on the main react-native JS thread? Thanks @terrysahaidak 

Single set will work just the same as runOnUI. So yeah, you can avoid it. The runOnJS is mostly for us to notify we run something asynchronously when we didn't want to

**Comment by likern** [comment]
> > Otherwise in a normal scenario you shouldn’t have to use runOnUI, right? If I’m just seeing an animated value on the main react-native JS thread? Thanks @terrysahaidak
> 
> Single set will work just the same as runOnUI. So yeah, you can avoid it. The runOnJS is mostly for us to notify we run something asynchronously when we didn't want to

Is there some measurements how fast / slow these async assignments? What general lag to expect?

**Comment by dhirajanand014** [comment]
How to resolve this issue. My app crashes when -

a.i want to focus an input text on finished.

`input_search_box_translate_x.value = withSpring(isShowInputBox && 1 || width, { damping: 20 }, (finished) => { runOnJS(focusAndBlurInputBox)(isShowInputBox, inputTextRef); <-- Guessing this is causing the app to crash. })`

focusAndBlurInputBox function - 
export const focusAndBlurInputBox = (isShowInputBox, inputTextRef) => {
    'worklet';
    if (!isShowInputBox) {
        inputTextRef.current.clear();
        inputTextRef.current.blur();
    } else {
        inputTextRef.current.focus();
    }
}

b. Also the same should also work when i need to update the state by calling setValues state hook when on finished.

`content_translate_y.value= withSpring(isShowInputBox && 1 || height, { damping: 20 }, (finished) => { //how to get the following working? setSearchValues({ ...searchValues, searchForPostId: post.postId }); });`

**Comment by dhirajanand014** [comment]
> How to resolve this issue. My app crashes when -
> 
> a.i want to focus an input text on finished.
> 
> `input_search_box_translate_x.value = withSpring(isShowInputBox && 1 || width, { damping: 20 }, (finished) => { runOnJS(focusAndBlurInputBox)(isShowInputBox, inputTextRef); <-- Guessing this is causing the app to crash. })`
> 
> `focusAndBlurInputBox function - export const focusAndBlurInputBox = (isShowInputBox, inputTextRef) => { 'worklet'; if (!isShowInputBox) { inputTextRef.current.clear(); inputTextRef.current.blur(); } else { inputTextRef.current.focus(); } }`
> 
> b. Also the same should also work when i need to update the state by calling setValues state hook when on finished.
> 
> `content_translate_y.value= withSpring(isShowInputBox && 1 || height, { damping: 20 }, (finished) => { //how to get the following working? setSearchValues({ ...searchValues, searchForPostId: post.postId }); });`

Any Update?

**Comment by terrysahaidak** [comment]
Could you please provide us at least the error message and some stacktrace?

**Comment by dhirajanand014** [comment]
> Could you please provide us at least the error message and some stack trace?

There is no error or any stack trace. However, the app crashes when i put in the `runOnJS(focusAndBlurInputBox)(isShowInputBox, inputTextRef);` or any `setState()` function in the finished block. If none of these are present and just like how the example has the console.log() in the finished block, there are no issues.

I'm referring the tar builds to actually use the `runOnJS()` function. With the usual npm package - 2.0.0.alpha.8 => i used to get the below error - 

![97704621-104ecd00-1ab3-11eb-8aa2-580f568e4522](https://user-images.githubusercontent.com/29733508/99139051-69923100-265b-11eb-98f6-1ad96a1bebba.png)

Please let know the correct usage of the finished block in the callback in the withSpring Animation. Particularly setting the input text focus and setting the state of React hooks.

**Comment by wcandillon** [comment]
This is fixed, right? feel free to reopen if you disagree.

**Comment by Cetger** [comment]
> This is fixed, right? feel free to reopen if you disagree.

I have still the same error. Im just following tutorial to learn reanimated. And below code is from one of these tutorials. Im getting error when i click button and also as I said I'm new on react-native, is there anyone help me? Why this code isnt correct?

```
"react-native-reanimated": "2.0.0-rc.1",

import React from 'react';
import { View, Button } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming,
  useDerivedValue,
} from 'react-native-reanimated';

export default function AnimatedStyleUpdateExample() {
  const progress=useSharedValue(0)
  const translateX=useDerivedValue(()=>{
    return progress.value*100
  })

  const animatedStyles=useAnimatedStyle(()=>{
    return {
      transform:[{translateX:translateX.value}]
    };
  });

  return (
    <View>
      <Animated.View style={[{height:100,width:100,backgroundColor:"red"}, animatedStyles]} />
      <Button onPress={() => (progress.value = withTiming( Math.random()))} title="Hey" />
    </View>
  );
}
```

**Comment by duducv** [comment]
I had the same issue, and the reason was wrong syntax when calling runOnJS
example:
right way -> runOnJS(console.log)('JS thread')

my error -> runOnJS(console.log('JS thread'));

**Comment by Crashtor** [comment]
This error is still present. Any workarounds until this is fixed?

**Comment by terrysahaidak** [comment]
> This error is still present. Any workarounds until this is fixed?

unfortunately, we won't be able to help without reproducing example code.

**Comment by duducv** [comment]
> > This is fixed, right? feel free to reopen if you disagree.
> 
> I have still the same error. Im just following tutorial to learn reanimated. And below code is from one of these tutorials. Im getting error when i click button and also as I said I'm new on react-native, is there anyone help me? Why this code isnt correct?
> 
> ```
> "react-native-reanimated": "2.0.0-rc.1",
> 
> import React from 'react';
> import { View, Button } from 'react-native';
> import Animated, {
>   useSharedValue,
>   useAnimatedStyle,
>   withTiming,
>   useDerivedValue,
> } from 'react-native-reanimated';
> 
> export default function AnimatedStyleUpdateExample() {
>   const progress=useSharedValue(0)
>   const translateX=useDerivedValue(()=>{
>     return progress.value*100
>   })
> 
>   const animatedStyles=useAnimatedStyle(()=>{
>     return {
>       transform:[{translateX:translateX.value}]
>     };
>   });
> 
>   return (
>     <View>
>       <Animated.View style={[{height:100,width:100,backgroundColor:"red"}, animatedStyles]} />
>       <Button onPress={() => (progress.value = withTiming( Math.random()))} title="Hey" />
>     </View>
>   );
> }
> ```
> 
> 
You need set the duration props using with timing. Example: progress.value = with timing(Math.random(), {duration: 500}).

Where 500 are milliseconds.

**Comment by axe-z** [comment]
right way -> runOnJS(console.log)('smart str') hard crashes on latest "2.4.1" for me

**Comment by aklemen** [comment]
> right way -> runOnJS(console.log)('smart str') hard crashes on latest "2.4.1" for me

Try wrapping the `console.log` in a worklet and then call it using `runOnJS`.
Might work, althought this should only be neccessary for calling functions from external libraries.

> If you want to invoke some function from external library in runOnJS please wrap it into a separate function.

```typescript
const wrapper = (text: string) => {
  console.log('Running on JS thread:', text);
};

useDerivedValue(() => {
  runOnJS(wrapper)('some text');
});
```

**Comment by piaskowyk** [comment]
You don't need to wrap the console.log in runOnJs. The `console.log` is available for worklets.

**Comment by PrasathRavichandran** [comment]
I don't know why it is throwing an error during, calling the **wrapper function below the useDerivedValue hooks**,

### Working without error:
```
const wrapper = (text: string) => {
  console.log('Running on JS thread:', text);
};

useDerivedValue(() => {
  runOnJS(wrapper)('some text');
});
```

### not working, throwing ( undefined is not an object (evaluating 'fun.__callAsync') error)
```
useDerivedValue(() => {
  runOnJS(wrapper)('some text');
});

const wrapper = (text: string) => {
  console.log('Running on JS thread:', text);
};
```
Is positioning function really matter 🤔 @aklemen

**Comment by aklemen** [comment]
Yes, I think it maters.
When calling `useDerivedValue(...)`, the `wrapper` function that is passed to `runOnJS` is not yet defined.
You have to define it before passing it to `runOnJS`.
