### ISSUE TITLE
Reanimated 2 failed to create a worklet

### ISSUE THREAD

**Issue by Lg0gs** [software-mansion/react-native-reanimated#1713]
When I import `Animated` in my file, no matter I use it somewhere or not, every time it says that `Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?`.

My `babel.config.js`

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

I'm using `^2.0.0-rc.3` version.

**Comment by jakub-gonet** [comment]
This doesn't help us much, could you describe your environment in detail?

Also, have you cleared the node_modules, yarn & metro caches?

**Comment by Lg0gs** [comment]
I just created a clean RN project and followed [these](https://docs.swmansion.com/react-native-reanimated/docs/installation) instructions.

**package.json**

```
{
  "name": "reanimated_2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-reanimated": "^2.0.0-rc.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/runtime": "^7.12.13",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.19.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.65.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**babel.config.js**

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

**App.js**

```
import React from 'react';
import { SafeAreaView } from 'react-native';
import Animated from 'react-native-reanimated';

const App = () => {
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: 'red' }}>

    </SafeAreaView>
  )
}

export default App;

```
 And it givems me this error message.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/47741923/107685561-93d8a680-6cbd-11eb-9ac8-3ae8482b2e06.png">

**Comment by jakub-gonet** [comment]
That's strange. if that's a new RN project (so it doesn't contain proprietary code) then could you create a repo with it so I can test it locally?

**Comment by Lg0gs** [comment]
@jakub-gonet
https://github.com/Lg0gs/RNR-2

**Comment by hwhh** [comment]
Also seeing this in a fresh react-native app (using react-native-reanimated 2.0.0-rc.3)

**Comment by Lg0gs** [comment]
It’s solved now, I ran the app on the real device, it had no problem and then everything was ok in the simulator

**Comment by jakub-gonet** [comment]
I also can confirm it does work, so I'm going to close this issue.

**Comment by KauMah** [comment]
Hi, I am still experiencing the aforementioned error. This is my babel.config.js file:
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blacklist: null,
        whitelist: null,
        safe: true,
        allowUndefined: true,
      },
      'react-native-reanimated/plugin',
    ],
  ],
};

```
additionally, here is my package.json: 
```
{
  "name": "blah",
  "version": "0.0.1",
  ... (shortening file by removing scripts here)
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "1.2.32",
    "@fortawesome/free-regular-svg-icons": "5.15.1",
    "@fortawesome/free-solid-svg-icons": "5.15.1",
    "@fortawesome/react-native-fontawesome": "0.2.6",
    "@react-native-async-storage/async-storage": "1.13.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-mapbox-gl/maps": "8.1.0-rc10",
    "@react-navigation/bottom-tabs": "5.11.2",
    "@react-navigation/native": "5.8.10",
    "@react-navigation/stack": "5.12.8",
    "axios": "0.21.1",
    "buffer": "6.0.3",
    "formik": "2.2.6",
    "handler": "0.1.3",
    "javascript-time-ago": "2.3.4",
    "lodash": "4.17.20",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture": "0.2.0",
    "react-native-gesture-handler": "1.10.1",
    "react-native-image-crop-picker": "0.35.2",
    "react-native-permissions": "3.0.0",
    "react-native-reanimated": "2.0.0-rc.3",
    "react-native-redash": "16.0.8",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "2.16.1",
    "react-native-svg": "12.1.0",
    "react-native-toast-message": "1.4.3",
    "react-native-vector-icons": "8.0.0",
    "react-native-webp-format": "1.1.2",
    "react-redux": "7.2.2",
    "redux": "4.0.5",
    "rollbar-react-native": "0.9.1",
    "yup": "0.32.8"
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/runtime": "^7.12.13",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/javascript-time-ago": "2.0.1",
    "@types/jest": "^25.2.3",
    "@types/react-native": "^0.63.2",
    "@types/react-native-dotenv": "0.2.0",
    "@types/react-native-vector-icons": "^6.4.6",
    "@types/react-redux": "7.1.15",
    "@types/react-test-renderer": "^16.9.2",
    "@types/yup": "0.29.11",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "eslint-plugin-unused-imports": "1.0.1",
    "husky": "4.3.8",
    "jest": "^25.1.0",
    "lint-staged": "10.5.3",
    "metro-react-native-babel-preset": "0.64.0",
    "prettier": "2.2.1",
    "react-native-dotenv": "2.4.3",
    "react-test-renderer": "16.13.1",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

```

Is there any additional configuration that may be getting in the way of this package from working?

**Comment by enrickdaltro** [comment]
The same is happening to me :(
![Screen Shot 2021-02-25 at 15 40 39](https://user-images.githubusercontent.com/49761746/109200834-d0a5a280-777f-11eb-96e0-5b6d53adf3c4.png)

**Comment by systemlevel** [comment]
Same situation here:
<img width="899" alt="Screen Shot 2021-03-01 at 6 58 36 PM" src="https://user-images.githubusercontent.com/894983/109585131-26e84d80-7ac0-11eb-822f-136face1c31e.png">

**Comment by systemlevel** [comment]
`yarn start --reset-cache` helped in my case on Android.

**Comment by hitanshuGajjar20** [comment]
I am also getting the same issue even after following all the instruction
i have also tried to reset cache

can anyone help me Please

**Comment by hitanshuGajjar20** [comment]
> `yarn start --reset-cache` helped in my case on Android.

This is helping me too

**Comment by Lg0gs** [comment]
@hitanshuGajjar20 
Did you try to run the app on the real device?

**Comment by hitanshuGajjar20** [comment]
> @hitanshuGajjar20
> Did you try to run the app on the real device?

yes i did

**Comment by hitanshuGajjar20** [comment]
I just solved it, 
and its because I was using **npm** we strickly need to use **yarn**
After I install and clear the cache using yarn the problem was solved and everything was working fine

In short, we need to use **yarn compulsory**

**Comment by Lg0gs** [comment]
@hitanshuGajjar20 
Great, thanks, 'll keep it in mind. Btw, I switched to `yarn` a couple of days ago

**Comment by akinncar** [comment]
Same problem on android emulator, any fixes besides clean cache and re-install node_modules? doesn't work here ;/

**Comment by covahn** [comment]
Still an issue for me on a fresh `npx react-native init` project, have only used yarn to install dependecies, tried cleaning yarn cache. Both on a real ios device and simulator.

**Comment by neerajbagga** [comment]
I get this error when I use `createMaterialTopTabNavigator`. No problems when I use `createBottomTabNavigator`

```
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
```

I was earlier using npm install, but then I deleted the package.lock.json and re ran Yarn 
Also ran the following for good measures:
`yarn add @react-navigation/material-top-tabs react-native-tab-view`

Everytime I change from createBottomTabNavigator to createMaterialTopTabNavigator, I get the error: 
Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

**Comment by ebarahona** [comment]
here is what worked for me (in this order):

yarn cache clean
rm -rf node_modules
rm yarn.lock
yarn
cd ios 
pod update
pod install

**Comment by eleviven** [comment]
`npx react-native start --reset-cache` solved my issue

**Comment by erdemildiz** [comment]
+1

**Comment by Cyral** [comment]
Same issue, fresh new react native project

**Comment by iracanyes** [comment]
Had the same issue. I'm using `expo init myProject` for creating my project. 
With the command "yarn add react-native-reanimated", it define "react-native-reanimated: ^2.0.0" in dependencies
But installing the version "2.0.0-alpha.9.2" solved my issue. Don't know if it can help

**Comment by pjadavies** [comment]
None of these solutions has worked for me, and I'm surprised the bug is closed because "use npm instead of yarn" doesn't feel like a solution.

For anyone else in this situation, reverting to the last stable as @valfirst did ^^ seems to be the only surefire fix.

In package.json:
```
"dependencies": {
  "react-native-reanimated": "^1.13.2",
  ...
}

```

@jakub-gonet fyi in case this ongoing thread is muted for you

**Comment by edward2553** [comment]
> None of these solutions has worked for me, and I'm surprised the bug is closed because "use yarn instead of npm" doesn't feel like a solution. (Even if it did work, which it didn't for me.)
> 
> For anyone else in this situation, reverting to the last stable as @valfirst did ^^ seems to be the only surefire fix.
> 
> In package.json:
> 
> ```
> "dependencies": {
>   "react-native-reanimated": "^1.13.2",
>   ...
> }
> ```
> 
> @jakub-gonet fyi in case this ongoing thread is muted for you

Thanks a lot! that solution worked for me!

**Comment by jakub-gonet** [comment]
@jakub-gonet fyi in case this ongoing thread is muted for you

@pjadavies thanks, but no one in this thread prepared any other repro example so I only confirmed that @Lg0gs repro was working. We have _some_ problems with yarn / npm install but without any reproduction example, we can only guess what is happening. 

If somebody still experiences this problem try resetting your RN cache (removing node_modules, resetting Xcode / Gradle & metro caches), and if the problem persists, please open a new issue with some reproducible example.
