### ISSUE TITLE
Debug with Chrome Issue

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#2309]
I just started to use reanimated v2 on my project.

reanimated 2  version `2.2.0`  

When i try to open debugger in chrome it gives me this error below.

![Simulator Screen Shot - iPhone 12 - 2021-08-21 at 21 34 02](https://user-images.githubusercontent.com/44513402/130331889-6379ac06-3124-4b25-bab8-a41de2644adc.png)

**Comment by jakub-gonet** [comment]
Check out [the limitations section](https://docs.swmansion.com/react-native-reanimated/docs#known-problems-and-limitations) in our docs:
> As the library uses JSI for synchronous native methods access, remote debugging is no longer possible. You can use Flipper for debugging your JS code, however connecting debugger to JS context which runs on the UI thread is not currently supported.

@piaskowyk is working on fixing this but as of 2.2.0 this is still a limitation.

**Comment by grit96** [comment]
Is this fixed by https://github.com/software-mansion/react-native-reanimated/pull/2197?

**Comment by Bayramito** [comment]
not tested yet, will give it a try later.

**Comment by Bayramito** [comment]
I've tried with latest stable release 2.2.2 but still not working

**Comment by grit96** [comment]
@Bayramito according to the PR it was in 2.3.0-alpha so I presume it will be released in 2.3.0 stable.

**Comment by CTOverton** [comment]
Going on two months, any progress?

**Comment by alexfov** [comment]
2.3.0 the problem is still here
