### ISSUE TITLE
"Could not get BatchedBridge, make sure your bundle is packaged correctly" since react-native 0.65 using Release schema

### ISSUE THREAD

**Issue by truongngodang** [software-mansion/react-native-reanimated#2313]
## Description

I created a project from react-native template version 0.65, I built It's ok, but then when added reanimated2 and building and starting the app on IOS, I receive an error saying "Could not get BatchedBridge, make sure your bundle is packaged correctly". Whenever running on the Debug schema, the app successfully starts.
```
+ (void)runRunLoop
{
  @autoreleasepool {
    RCT_PROFILE_BEGIN_EVENT(RCTProfileTagAlways, @"-[RCTCxxBridge runJSRunLoop] setup", nil);

    // copy thread name to pthread name
    pthread_setname_np([NSThread currentThread].name.UTF8String);

    // Set up a dummy runloop source to avoid spinning
    CFRunLoopSourceContext noSpinCtx = {0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
    CFRunLoopSourceRef noSpinSource = CFRunLoopSourceCreate(NULL, 0, &noSpinCtx);
    CFRunLoopAddSource(CFRunLoopGetCurrent(), noSpinSource, kCFRunLoopDefaultMode);
    CFRelease(noSpinSource);

    RCT_PROFILE_END_EVENT(RCTProfileTagAlways, @"");

    // run the run loop
    while (kCFRunLoopRunStopped !=
           CFRunLoopRunInMode( com.facebook.react.JavaScript (9): "Could not get BatchedBridge, make sure your bundle is packaged correctly"
               kCFRunLoopDefaultMode, ((NSDate *)[NSDate distantFuture]).timeIntervalSinceReferenceDate, NO)) {
      RCTAssert(NO, @"not reached assertion"); // runloop spun. that's bad.
    }
  }
}
```

### Expected behavior

For react-native-reanimated 2.2.0 I expect react-native 0.65.0 to compile. I expect the app not to crash.

### Actual behavior & steps to reproduce

After added reanimated2, it crashed.

## Package versions

- React Native: 0.65.0
- React Native Reanimated: 2.2.0
- NodeJS: latest 
- Xcode: Latest
- Java & Gradle: Latest

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by lukasa1993** [comment]
this need quick love

**Comment by Gnative** [comment]
Maybe related to https://github.com/facebook/react-native/issues/32028

**Comment by piaskowyk** [comment]
Hey @truongngodang! 
The 2.2.0 version doesn't support RN65 yet. You should use 2.3.0-alpha.2 with support for RN65 or you can wait for a patch for 2.2.1 with support for RN65 - we want to release it this week.

**Comment by lukasa1993** [comment]
alpha.2 doesnt work either

**Comment by piaskowyk** [comment]
Ok, thanks for the info, so I reopen.

**Comment by BooYeu** [comment]
> Hey @truongngodang!
> The 2.2.0 version doesn't support RN65 yet. You should use 2.3.0-alpha.2 with support for RN65 or you can wait for a patch for 2.2.1 with support for RN65 - we want to release it this week.

I keep waiting for it, really really want to know when can I use 2.2.1. Thank you very much !!!!

**Comment by piaskowyk** [comment]
Hey @truongngodang 👋  The version 2.2.0 doesn't support `react-native@0.65`. If you want to use Reanimated with RN65 you should update it to 2.2.1 or 2.3.0-alpha.2+ 

We have just released 2.2.1 🎉

**Comment by adeem** [comment]
I m using `"react-native": "0.66.4"` and  `"react-native-reanimated": "^2.8.0",` and still getting this issue. Any help?

**Comment by buddyeorl** [comment]
same issue, react native "react-native": "0.68.5", and "react-native-reanimated": "~2.8.0",

**Comment by nandorojo** [comment]
I'm getting this with React Native 0.70.5 and Reanimated 2.41.4. Are those versions supposed to be compatible?

**Comment by scott-harrison** [comment]
Im getting the same error "Could not get BatchedBridge"

React Native: 0.71.14
React-native-reanimated: 3.5.4

Any ideas how to resolve? I have found that this issue has occurred since updating react native and reanimated to v3 from v2.

Also I discovered that by disabling hermes the error goes away.
