### ISSUE TITLE
AnimatedLayout android.view.WindowManager android.app.Activity.getWindowManager()' on a null object reference

### ISSUE THREAD

**Issue by TrungNguyen153** [software-mansion/react-native-reanimated#2351]
## Description
When using AnimatedLayout with react native navigation:
+ first screen use AnimatedLayout as Parent View
```
-example:
const LauncherScreen = () =>{
    return (
        <AnimatedLayout style={{flex: 1}}>
                <Animated.View style={{width: 100, height: 100}} entering={LightSpeedInLeft.duration(250)} />
                <Animated.View style={{width: 100, height: 100}} entering={LightSpeedInLeft.duration(250)} />
                <Animated.View style={{width: 100, height: 100}} entering={LightSpeedInLeft.duration(250)} />
      </AnimatedLayout>
    )
}
```
+ when press back from HARDWARE -> app close and throw error android.view.WindowManager android.app.Activity.getWindowManager()' on a null object reference... ( Flipper Crash Reporter )

### Temporary bug fix:
+ Hook back press from control react native navigation then use library react-native-exit-app exit app ( Normal exit will make app run into BackgroundMode and throw error above... this library kill app progress.
 ```
useFocusEffect(
    useCallback(() => {
      const onBackPress = () => {
        RNExitApp.exitApp();
        return true;
      };
      BackHandler.addEventListener('hardwareBackPress', onBackPress);
      return () => BackHandler.removeEventListener('hardwareBackPress', onBackPress);
    }, [])
  );
```

### Expected behavior
- App close without throw any error

### Actual behavior & steps to reproduce
- Example above

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.2
- NodeJS: 16.4.2
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [ ] iOS ( Not test yet )
- [ ] Web ( Not test yet )

**Comment by jmysliv** [comment]
Hi @TrungNguyen153! We have just released `2.3.0-alpha.3` without `AnimatedLayout` and I think your problem might be gone. Can you check it and let me know?

**Comment by TrungNguyen153** [comment]
Hi @jmysliv, i check again with new 2.3.0-alpha.3. The bug still exists.

**Comment by TrungNguyen153** [comment]
Last check beta 1, error above still present
