### ISSUE TITLE
[2.3.0-beta.1] React-Navigation Back Button unmounts previous screen with Reanimated

### ISSUE THREAD

**Issue by SultanTanirkul** [software-mansion/react-native-reanimated#2460]
## Description

After updating reanimated to the latest version 2.3.0.-beta.1 from 2.2.2 the navigation between existing screens removes interactivity as well as some styles from the screen (presumably unmounts previous screen when back button is pressed). Simple example is navigating from screen 'A' to 'B' and going back causes this bug or issue. It is only seems to affect native stack navigator.

Everything is working just fine on version 2.2.2

### Expected behavior
Navigation from one screen to another and then using back button shows the previous screen as it has been before navigating.

### Actual behavior & steps to reproduce
Navigation from one screen to another and then using back button unmounts the previous screen.

## Snack or minimal code example

https://github.com/SultanTanirkul/navigation-reanimated-bug

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.1
- @react-navigation/native: 6.0.4
- @react-navigation/native-stack: 6.2.2
- react-native-screens": 3.7.2

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by exneval** [comment]
I'm also able to reproduce the issue in 2.3.0-beta.1 with @react-navigation/native-stack 6.2.2 and react-native-screens 3.7.2

**Comment by mateusz1913** [comment]
I am also able to reproduce similar issue, you can check example repo https://github.com/mateusz1913/react-native-avoid-softinput/tree/master/example 

## Package versions
- @react-navigation/native: "6.0.3",
- @react-navigation/native-stack: "6.2.0",
- react: "17.0.2",
- react-native: "0.65.1",
- react-native-reanimated: "^2.3.0-beta.1",
- react-native-safe-area-context: "3.3.2",
- react-native-screens: "3.7.2"

When screen is dismissed (via back button or hardware back press), it is pushed again on screen, which makes app not responding to any user's input.

here is gif of incorrect behavior
![bug](https://user-images.githubusercontent.com/25980166/134942948-6e859991-e213-4f37-89a1-208e5887159a.gif)

**Comment by evgenusov** [comment]
Same for me!

**Comment by Ralisson-Mattias** [comment]
Same problem here

**Comment by nazrdogan** [comment]
Same for me

**Comment by tominou** [comment]
Same issue here.
`react-native 0.66.0`
`react-native-reanimated 2.3.0-beta.1`

**Comment by yaredtaye** [comment]
I confirm Same issue . 
react-native 0.66.0
react-native-reanimated 2.3.0-beta.2


When will the fix be available?

**Comment by ruairioliverwv** [comment]
This resolves it for me: https://github.com/software-mansion/react-native-reanimated/issues/2477#issuecomment-933369904

**Comment by nazacity** [comment]
same for me

**Comment by savv** [comment]
I guess many people upgraded to 2.3.0-beta.x only because it supports RN 0.66.0. A new patch release that supports it would unblock all those many people.

**Comment by hannojg** [comment]
Just tested whether #2486 has fixed this issue as stated [here](https://github.com/software-mansion/react-native-reanimated/issues/2457#issuecomment-928068725), but unfortunately, it didn't.

**Comment by bilarslan** [comment]
Just tested with v2.2.3 on android and the issue solved 🎉🎉🎉

**Comment by albinekb** [comment]
Thank you for your temporary version @savv! I have updated to 2.2.3 on Android now and the issue is solved 🎉

**Comment by Darapsas** [comment]
The issue seems to still persist on the latest package versions:
```json
"react-native": "0.66.1",
"react-native-reanimated": "2.3.0-beta.3",
```

**Comment by 000xuandu** [comment]
Same issue:
    
```
"react-native": "0.64.0",
"react-native-reanimated": "^2.3.0-beta.2",
```

**Comment by bilaltahseen** [comment]
Same error for me , however running in emulator is fine but not working in real device , I am testing on Samsung Note 5
