### ISSUE TITLE
[iOS] App randomly hangs since upgrading from `2.2.2` to `2.3.0-beta.2` (crash reports included)

### ISSUE THREAD

**Issue by SimpleCreations** [software-mansion/react-native-reanimated#2505]
## Description

I'm experiencing frequent app hangs an iOS 12.5.4 device since upgrading to RN 0.66 and consequently to Reanimated 2.3.0-beta.2. They seem to happen randomly not being caused by any particular user actions.

Below are the 3 crash reports I've received. What they all seem to have in common is some call from `NativeProxy.mm`.

```
App Hang: The app was terminated while unresponsive

0  libsystem_kernel.dylib  ___psynch_mutexwait
1  libsystem_pthread.dylib __pthread_mutex_firstfit_lock_wait
2  libsystem_pthread.dylib __pthread_mutex_firstfit_lock_slow$VARIANT$mp
3  libc++.1.dylib          std::__1::recursive_mutex::lock()
4  [redacted]              lock_guard (__mutex_base:91:27)
5  [redacted]              ~StoreUser (JSIStoreValueUser.cpp:45:22)
6  [redacted]              ~ShareableValue (ShareableValue.h:20:7)
7  [redacted]              __release_shared (memory:2506:9)
8  [redacted]              ~shared_ptr (memory:3236:1)
9  [redacted]              __deallocate_node (__hash_table:1580:9)
10 [redacted]              ~__hash_table (__hash_table:1519:5)
11 [redacted]              ~__hash_table (__hash_table:1511:1)
12 [redacted]              __release_shared (memory:2506:9)
13 [redacted]              ~shared_ptr (memory:3236:1)
14 [redacted]              operator() (memory:1428:5)
15 [redacted]              __release_shared (memory:2506:9)
16 [redacted]              ~shared_ptr (memory:3236:1)
17 [redacted]              __deallocate_node (__hash_table:1580:9)
18 [redacted]              ~__hash_table (__hash_table:1519:5)
19 [redacted]              ~__hash_table (__hash_table:1511:1)
20 [redacted]              __release_shared (memory:2506:9)
21 [redacted]              ~shared_ptr (memory:3236:1)
22 [redacted]              operator() (memory:1428:5)
23 [redacted]              __release_shared (memory:2506:9)
24 [redacted]              ~shared_ptr (memory:3236:1)
25 [redacted]              __deallocate_node (__hash_table:1580:9)
26 [redacted]              ~__hash_table (__hash_table:1519:5)
27 [redacted]              ~__hash_table (__hash_table:1511:1)
28 [redacted]              __release_shared (memory:2506:9)
29 [redacted]              ~shared_ptr (memory:3236:1)
30 JavaScriptCore          JSC::JSCallbackObject<JSC::JSDestructibleObject>::destroy(JSC::JSCell*)
31 JavaScriptCore          void JSC::MarkedBlock::Handle::specializedSweep<true, (JSC::MarkedBlock::Handle::EmptyMode)1, (JSC::MarkedBlock::Handle::SweepMode)0, (JSC::MarkedBlock::Handle::SweepDestructionMode)1, (JSC::MarkedBlock::Handle::ScribbleMode)0, (JSC::MarkedBlock::Handle::NewlyAllocatedMode)1, (JSC::MarkedBlock::Handle::MarksMode)1, JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::MarkedBlock::Handle::EmptyMode, JSC::MarkedBlock::Handle::SweepMode, JSC::MarkedBlock::Handle::SweepDestructionMode, JSC::MarkedBlock::Handle::ScribbleMode, JSC::MarkedBlock::Handle::NewlyAllocatedMode, JSC::MarkedBlock::Handle::MarksMode, JSC::JSDestructibleObjectDestroyFunc const&)
32 JavaScriptCore          void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::JSDestructibleObjectDestroyFunc const&)::{lambda()#1}::operator()() const
33 JavaScriptCore          void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::JSDestructibleObjectDestroyFunc const&)
34 JavaScriptCore          JSC::JSDestructibleObjectHeapCellType::finishSweep(JSC::MarkedBlock::Handle&, JSC::FreeList*)
35 JavaScriptCore          JSC::MarkedBlock::Handle::sweep(JSC::FreeList*)
36 JavaScriptCore          JSC::BlockDirectory::sweep()
37 JavaScriptCore          JSC::MarkedSpace::sweep()
38 JavaScriptCore          JSC::Heap::sweepSynchronously()
39 JavaScriptCore          JSC::Heap::finalize()
40 JavaScriptCore          JSC::Heap::handleNeedFinalize(unsigned int)
41 JavaScriptCore          JSC::Heap::acquireAccessSlow()
42 JavaScriptCore          JSC::JSLock::didAcquireLock()
43 JavaScriptCore          JSC::JSLockHolder::JSLockHolder(JSC::ExecState*)
44 JavaScriptCore          _JSValueMakeString
45 [redacted]              valueRef (JSCRuntime.cpp:1416:12)
46 [redacted]              ArgsConverter (JSCRuntime.cpp:1227:27)
47 [redacted]              ArgsConverter (JSCRuntime.cpp:1219:71)
48 [redacted]              call (jsi-inl.h:228:18)
49 [redacted]              ___ZN10reanimated22createReanimatedModuleENSt3__110shared_ptrIN8facebook5react11CallInvokerEEE_block_invoke.15 (NativeProxy.mm:188:28)
50 [redacted]              -[REAAnimationsManager onViewCreate:after:] (REAAnimationsManager.m:260:7)
51 [redacted]              __51-[REAUIManager uiBlockWithLayoutUpdateForRootView:]_block_invoke.107 (REAUIManager.mm:287:9)
52 [redacted]              __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke (RCTUIManager.m:1198:9)
53 [redacted]              __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.426 (RCTUIManager.m:1218:5)
54 libdispatch.dylib       __dispatch_call_block_and_release
55 libdispatch.dylib       __dispatch_client_callout
56 libdispatch.dylib       __dispatch_main_queue_callback_4CF$VARIANT$mp
57 CoreFoundation          ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
58 CoreFoundation          ___CFRunLoopRun
59 CoreFoundation          _CFRunLoopRunSpecific
60 GraphicsServices        _GSEventRunModal
61 UIKitCore               _UIApplicationMain
62 [redacted]              main (main.m:7:12)
63 libdyld.dylib           _start
```

```
App Hang: The app was terminated while unresponsive

0  libsystem_kernel.dylib  ___psynch_mutexwait
1  libsystem_pthread.dylib __pthread_mutex_firstfit_lock_wait
2  libsystem_pthread.dylib __pthread_mutex_firstfit_lock_slow$VARIANT$mp
3  libc++.1.dylib          std::__1::recursive_mutex::lock()
4  [redacted]              lock_guard (__mutex_base:91:27)
5  [redacted]              ~StoreUser (JSIStoreValueUser.cpp:45:22)
6  [redacted]              ~ShareableValue (ShareableValue.h:20:7)
7  [redacted]              __release_shared (memory:2506:9)
8  [redacted]              ~shared_ptr (memory:3236:1)
9  [redacted]              __deallocate_node (__hash_table:1580:9)
10 [redacted]              ~__hash_table (__hash_table:1519:5)
11 [redacted]              ~__hash_table (__hash_table:1511:1)
12 [redacted]              __release_shared (memory:2506:9)
13 [redacted]              ~shared_ptr (memory:3236:1)
14 JavaScriptCore          JSC::JSCallbackObject<JSC::JSDestructibleObject>::destroy(JSC::JSCell*)
15 JavaScriptCore          void JSC::MarkedBlock::Handle::specializedSweep<true, (JSC::MarkedBlock::Handle::EmptyMode)1, (JSC::MarkedBlock::Handle::SweepMode)0, (JSC::MarkedBlock::Handle::SweepDestructionMode)1, (JSC::MarkedBlock::Handle::ScribbleMode)0, (JSC::MarkedBlock::Handle::NewlyAllocatedMode)1, (JSC::MarkedBlock::Handle::MarksMode)1, JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::MarkedBlock::Handle::EmptyMode, JSC::MarkedBlock::Handle::SweepMode, JSC::MarkedBlock::Handle::SweepDestructionMode, JSC::MarkedBlock::Handle::ScribbleMode, JSC::MarkedBlock::Handle::NewlyAllocatedMode, JSC::MarkedBlock::Handle::MarksMode, JSC::JSDestructibleObjectDestroyFunc const&)
16 JavaScriptCore          void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::JSDestructibleObjectDestroyFunc const&)::{lambda()#1}::operator()() const
17 JavaScriptCore          void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::JSDestructibleObjectDestroyFunc const&)
18 JavaScriptCore          JSC::JSDestructibleObjectHeapCellType::finishSweep(JSC::MarkedBlock::Handle&, JSC::FreeList*)
19 JavaScriptCore          JSC::MarkedBlock::Handle::sweep(JSC::FreeList*)
20 JavaScriptCore          JSC::BlockDirectory::sweep()
21 JavaScriptCore          JSC::MarkedSpace::sweep()
22 JavaScriptCore          JSC::Heap::sweepSynchronously()
23 JavaScriptCore          JSC::Heap::finalize()
24 JavaScriptCore          JSC::Heap::handleNeedFinalize(unsigned int)
25 JavaScriptCore          JSC::Heap::acquireAccessSlow()
26 JavaScriptCore          JSC::JSLock::didAcquireLock()
27 JavaScriptCore          JSC::JSLockHolder::JSLockHolder(JSC::ExecState*)
28 JavaScriptCore          _JSValueUnprotect
29 [redacted]              invalidate (JSCRuntime.cpp:587:5)
30 [redacted]              ~Pointer (jsi.h:366:13)
31 [redacted]              operator() (NativeProxy.mm:97:31)
32 [redacted]              operator() (functional:1885:16)
33 [redacted]              execute (MapperRegistry.cpp:26:15)
34 [redacted]              onEvent (NativeReanimatedModule.cpp:242:21)
35 [redacted]              ___ZN10reanimated22createReanimatedModuleENSt3__110shared_ptrIN8facebook5react11CallInvokerEEE_block_invoke.41 (NativeProxy.mm:234:13)
36 [redacted]              __33-[REANodesManager dispatchEvent:]_block_invoke (REANodesManager.m:466:7)
37 libdispatch.dylib       __dispatch_call_block_and_release
38 libdispatch.dylib       __dispatch_client_callout
39 libdispatch.dylib       __dispatch_main_queue_callback_4CF$VARIANT$mp
40 CoreFoundation          ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
41 CoreFoundation          ___CFRunLoopRun
42 CoreFoundation          _CFRunLoopRunSpecific
43 GraphicsServices        _GSEventRunModal
44 UIKitCore               _UIApplicationMain
45 [redacted]              main (main.m:7:12)
46 libdyld.dylib           _start
```

```
App Hang: The app was terminated while unresponsive

0  libsystem_kernel.dylib  ___psynch_mutexwait
1  libsystem_pthread.dylib __pthread_mutex_firstfit_lock_wait
2  libsystem_pthread.dylib __pthread_mutex_firstfit_lock_slow$VARIANT$mp
3  libc++.1.dylib          std::__1::recursive_mutex::lock()
4  [redacted]              lock_guard (__mutex_base:91:27)
5  [redacted]              ~StoreUser (JSIStoreValueUser.cpp:45:22)
6  [redacted]              ~ShareableValue (ShareableValue.h:20:7)
7  [redacted]              __release_shared (memory:2506:9)
8  [redacted]              ~shared_ptr (memory:3236:1)
9  [redacted]              __deallocate_node (__hash_table:1580:9)
10 [redacted]              ~__hash_table (__hash_table:1519:5)
11 [redacted]              ~__hash_table (__hash_table:1511:1)
12 [redacted]              __release_shared (memory:2506:9)
13 [redacted]              ~shared_ptr (memory:3236:1)
14 JavaScriptCore          JSC::JSCallbackObject<JSC::JSDestructibleObject>::destroy(JSC::JSCell*)
15 JavaScriptCore          void JSC::MarkedBlock::Handle::specializedSweep<true, (JSC::MarkedBlock::Handle::EmptyMode)1, (JSC::MarkedBlock::Handle::SweepMode)0, (JSC::MarkedBlock::Handle::SweepDestructionMode)1, (JSC::MarkedBlock::Handle::ScribbleMode)0, (JSC::MarkedBlock::Handle::NewlyAllocatedMode)1, (JSC::MarkedBlock::Handle::MarksMode)1, JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::MarkedBlock::Handle::EmptyMode, JSC::MarkedBlock::Handle::SweepMode, JSC::MarkedBlock::Handle::SweepDestructionMode, JSC::MarkedBlock::Handle::ScribbleMode, JSC::MarkedBlock::Handle::NewlyAllocatedMode, JSC::MarkedBlock::Handle::MarksMode, JSC::JSDestructibleObjectDestroyFunc const&)
16 JavaScriptCore          void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::JSDestructibleObjectDestroyFunc const&)::{lambda()#1}::operator()() const
17 JavaScriptCore          void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>(JSC::FreeList*, JSC::JSDestructibleObjectDestroyFunc const&)
18 JavaScriptCore          JSC::JSDestructibleObjectHeapCellType::finishSweep(JSC::MarkedBlock::Handle&, JSC::FreeList*)
19 JavaScriptCore          JSC::MarkedBlock::Handle::sweep(JSC::FreeList*)
20 JavaScriptCore          JSC::BlockDirectory::sweep()
21 JavaScriptCore          JSC::MarkedSpace::sweep()
22 JavaScriptCore          JSC::Heap::sweepSynchronously()
23 JavaScriptCore          JSC::Heap::finalize()
24 JavaScriptCore          JSC::Heap::handleNeedFinalize(unsigned int)
25 JavaScriptCore          JSC::Heap::acquireAccessSlow()
26 JavaScriptCore          JSC::JSLock::didAcquireLock()
27 JavaScriptCore          JSC::JSLockHolder::JSLockHolder(JSC::VM&)
28 JavaScriptCore          _JSContextGetGlobalObject
29 [redacted]              global (JSCRuntime.cpp:443:23)
30 [redacted]              ___ZN10reanimated22createReanimatedModuleENSt3__110shared_ptrIN8facebook5react11CallInvokerEEE_block_invoke.41 (NativeProxy.mm:231:43)
31 [redacted]              __33-[REANodesManager dispatchEvent:]_block_invoke (REANodesManager.m:466:7)
32 [redacted]              RCTExecuteOnMainQueue (RCTUtils.m:262:5)
33 [redacted]              -[REANodesManager dispatchEvent:] (REANodesManager.m:458:5)
34 [redacted]              -[REAEventDispatcher sendEvent:] (REAEventDispatcher.m:10:3)
35 [redacted]              __createEventSetter_block_invoke_2 (RCTComponentData.m:136:11)
36 [redacted]              -[RNSScreenView notifyWillDisappear] (RNSScreen.m:255:5)
37 [redacted]              -[RNSScreen viewWillDisappear:] (RNSScreen.m:597:5)
38 UIKitCore               -[UIViewController _setViewAppearState:isAnimating:]
39 UIKitCore               -[UIViewController __viewWillDisappear:]
40 UIKitCore               -[UINavigationController _startCustomTransition:]
41 UIKitCore               -[UINavigationController _startDeferredTransitionIfNeeded:]
42 UIKitCore               -[UINavigationController __viewWillLayoutSubviews]
43 UIKitCore               -[UILayoutContainerView layoutSubviews]
44 UIKitCore               -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
45 QuartzCore              -[CALayer layoutSublayers]
46 QuartzCore              CA::Layer::layout_if_needed(CA::Transaction*)
47 QuartzCore              CA::Context::commit_transaction(CA::Transaction*)
48 QuartzCore              CA::Transaction::commit()
49 UIKitCore               __afterCACommitHandler
50 CoreFoundation          ___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
51 CoreFoundation          ___CFRunLoopDoObservers
52 CoreFoundation          ___CFRunLoopRun
53 CoreFoundation          _CFRunLoopRunSpecific
54 GraphicsServices        _GSEventRunModal
55 UIKitCore               _UIApplicationMain
56 [redacted]              main (main.m:7:12)
57 libdyld.dylib           _start
```

### Expected behavior

App doesn't hang

### Actual behavior & steps to reproduce

Frequent app hangs occur

## Snack or minimal code example

N/A

## Package versions

- React Native: 0.66.0
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: 16.6.0
- Xcode: 13.0
- Java & Gradle: N/A

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Thanks for the report! I'm currently working on this. I will let you know about updates.

**Comment by enahum** [comment]
Definitely seen this, and not sure if this helps but taking the same exact steps a third time on the app I'm working on got this instead
![image](https://user-images.githubusercontent.com/6757047/136481565-7289766a-ba8e-4518-8f41-08022c97bffb.png)

**Comment by MonsterAnan** [comment]
So do I,  upgrading from 2.2.2 to 2.3.0-beta.2, iOS App sometime crash.

**Comment by wibb36** [comment]
iOS app crashes on 2.3.0-beta.1

**Comment by ShivamJoker** [comment]
Same happening with my app ass well It crashes
I thought this would have been fixed by now.

The lower version has the issue too.

**Comment by terrysahaidak** [comment]
Anyone reporting this try this patch. You can edit these files directly from xcode in Development Pods directory.

https://github.com/software-mansion/react-native-reanimated/commit/7883fc1f89c8a662b4ce030416231d3de9405b6e

**Comment by parasharrajat** [comment]
The patch is released in 2.3.0-beta.3 but I am still facing this issue. Is anyone actively looking for a solution to this issue?
Thank you.

**Comment by piaskowyk** [comment]
Is this issue still on 2.3.1?

**Comment by piaskowyk** [comment]
I think that problem is resolved, feel free to notify me if the problem still occurs.
