### ISSUE TITLE
[ios] Orphaned view remains after (react native's) modal dismissed

### ISSUE THREAD

**Issue by superguineapig** [software-mansion/react-native-reanimated#2538]
## Description

Once a RN Modal has been displayed, a "zombie" `UITransitionView` (with children) is left-over after the modal's dismissal. Depending upon the modal's transparency, the zombie view may or may not visually obscure the entire screen. In either case this view will "swallow" all touch events rendering the app unusable thereafter. 

#### Note
[This issue](https://github.com/facebook/react-native/issues/32329) has been making the rounds in several repos lately, and it appears `react-native-reanimated` is common among several reports. It is also being referenced in other issues in this repository, but I wanted to create a separate issue to elevate visibility on a minimal repro case, as the others include several other deps and may have unrelated problems.

### Expected behavior

React native modals are dismissed without leaving behind orphaned (UIKit) views.

### Actual behavior & steps to reproduce

When `react-native-reanimated` is present (package.json + pod installed), modals do not dismiss properly. More specifically, the dismissal animation appears to work properly, but there are left over (UIKit) views/controllers on the display hierarchy which obscure the rest of the screen and swallow touch events preventing further interaction.

#### Minimal *working* steps

1. Start with a fresh React Native project e.g. `npx react-native init Foo`
2. Replace `App.js` contents with the canonical Modal example for RN 0.66 [here](https://reactnative.dev/docs/modal)
3. Build and run on iOS simulator (w/out debugging)
4. Observe that you are able to open and dismiss the modal *repeatedly* as expected.

#### To Experience the issue
_starting after completing  working steps above_

1. `yarn/npm` install `react-native-reanimated@2.3.0-beta.2` _other versions may also apply; issue presents with reanimated2 and RN 0.66_
2. `pod install`
3. Clean, rebuild, run again
4. Observe that you are able to dismiss the modal once, and that the application will not respond to touch events anymore
5. `Capture View Hierarchy` in XCode and observe the left over orphaned UIKit views.

<img width="309" alt="viewstack" src="https://user-images.githubusercontent.com/4808737/137190544-c0cce284-00dc-4fea-9aeb-6f0de1532841.png">

## Snack or minimal code example
_snack does not reproduce the issue_

### App.js
Taken directly from react native example [page](https://reactnative.dev/docs/modal)
```jsx
import React, { useState } from "react";
import { Alert, Modal, StyleSheet, Text, Pressable, View } from "react-native";

const App = () => {
  const [modalVisible, setModalVisible] = useState(false);
  return (
    <View style={styles.centeredView}>
      <Modal
        animationType="slide"
        transparent={true}
        visible={modalVisible}
        onRequestClose={() => {
          Alert.alert("Modal has been closed.");
          setModalVisible(!modalVisible);
        }}
      >
        <View style={styles.centeredView}>
          <View style={styles.modalView}>
            <Text style={styles.modalText}>Hello World!</Text>
            <Pressable
              style={[styles.button, styles.buttonClose]}
              onPress={() => setModalVisible(!modalVisible)}
            >
              <Text style={styles.textStyle}>Hide Modal</Text>
            </Pressable>
          </View>
        </View>
      </Modal>
      <Pressable
        style={[styles.button, styles.buttonOpen]}
        onPress={() => setModalVisible(true)}
      >
        <Text style={styles.textStyle}>Show Modal</Text>
      </Pressable>
    </View>
  );
};

const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center"
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center"
  }
});

export default App;
```

## Package versions

From `package.json`
```json
{
...
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.66.0",
    "react-native-reanimated": "^2.3.0-beta.2"
  },
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@babel/runtime": "^7.15.4",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^27.2.5",
    "eslint": "^8.0.0",
    "jest": "^27.2.5",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  }
...
}

```

- React Native: 0.66.0
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: 12.20.1
- Xcode: 13.0 (13A233)
- Java & Gradle: N/A

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by rodgomesc** [comment]
any progress on that?, `2.3.0-beta.3`, don't seems to cause any effect on this.

![image](https://user-images.githubusercontent.com/4893591/137961070-9ba6a1c6-5898-40ef-9c75-2a74ee270ac2.png)

**Comment by Sanglepp** [comment]
Is there any progress on this? I would be happy to help out if possible as this is a blocker issue in my app.

**Comment by piaskowyk** [comment]
Probably this PR will fix it - https://github.com/software-mansion/react-native-reanimated/pull/2617 but I need to check it.

**Comment by piaskowyk** [comment]
Probably fixed with this PR - https://github.com/software-mansion/react-native-reanimated/pull/2581 but I need to check it.

**Comment by Sanglepp** [comment]
> Probably fixed with this PR - #2581 but I need to check it.

This fixes the modal issue but the back navigation issue still persists. Happens on a screen with longer scrollview.

**Comment by piaskowyk** [comment]
Fixed with - https://github.com/software-mansion/react-native-reanimated/pull/2581

**Comment by acollazomayer** [comment]
HI! @piaskowyk any ideas when this is going to be released?
