### ISSUE TITLE
[android] URGENT -> Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference

### ISSUE THREAD

**Issue by mwegener-com** [software-mansion/react-native-reanimated#2702]
## Description
A clean expo-dev-client app crashes on startup in android simulator (working fine on iOS)

this issue occurs on version 2.3.0 and above and it's OK on lower versions

### Expected behavior
app working fine.

### Actual behavior & steps to reproduce
clone this repo: https://github.com/mwegener-com/test2
change reanimated to 2.3.0
expo run:android --device (api 30)
see logcat

```
2021-12-08 04:36:38.574 5667-5667/com.mwegener.cabernetco E/unknown:ReactNative: Unable to launch logbox because react was unable to create the root view
2021-12-08 04:36:38.889 5667-5667/com.mwegener.cabernetco E/unknown:ReactInstanceManager: destroyRootView called
2021-12-08 04:36:38.889 5667-5667/com.mwegener.cabernetco E/unknown:ReactInstanceManager: destroyRootView called, unmountReactApplication
2021-12-08 04:36:39.382 5667-5782/com.mwegener.cabernetco E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.notifyWebSocketFailed(WebSocketModule.java:340)
        at com.facebook.react.modules.websocket.WebSocketModule.access$200(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onFailure(WebSocketModule.java:175)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$1.onFailure(RealWebSocket.java:216)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-12-08 04:36:40.466 5667-5749/com.mwegener.cabernetco E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by BlobModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.blob.BlobModule.addNetworkingHandler(BlobModule.java:300)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-12-08 04:36:40.990 5667-5788/com.mwegener.cabernetco E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.notifyWebSocketFailed(WebSocketModule.java:340)
        at com.facebook.react.modules.websocket.WebSocketModule.access$200(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onFailure(WebSocketModule.java:175)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$1.onFailure(RealWebSocket.java:216)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-12-08 04:36:41.003 5667-5749/com.mwegener.cabernetco E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by Timing
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.core.TimingModule.access$000(TimingModule.java:22)
        at com.facebook.react.modules.core.TimingModule$BridgeTimerManager.callTimers(TimingModule.java:28)
        at com.facebook.react.modules.core.JavaTimerManager.createAndMaybeCallTimer(JavaTimerManager.java:341)
        at com.facebook.react.modules.core.TimingModule.createTimer(TimingModule.java:91)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-12-08 04:36:41.012 5667-5790/com.mwegener.cabernetco E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onOpen(WebSocketModule.java:156)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:208)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-12-08 04:36:41.045 5667-5749/com.mwegener.cabernetco E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by Networking
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.network.NetworkingModule.getEventEmitter(NetworkingModule.java:767)
        at com.facebook.react.modules.network.NetworkingModule.sendRequestInternal(NetworkingModule.java:273)
        at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:243)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-12-08 04:36:41.057 5667-5667/com.mwegener.cabernetco E/unknown:ReactNative: Unable to handle Exception - catalystInstanceVariableExists: true - isCatalystInstanceAlive: true - hasExceptionHandler: true
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.AnimationsManager.isLayoutAnimationEnabled(AnimationsManager.java:507)
        at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.isLayoutAnimationEnabled(ReanimatedNativeHierarchyManager.java:191)
        at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:266)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:211)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:977)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
2021-12-08 04:36:41.058 5667-5667/com.mwegener.cabernetco E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mwegener.cabernetco, PID: 5667
    java.lang.IllegalStateException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:387)
        at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:394)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:33)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.AnimationsManager.isLayoutAnimationEnabled(AnimationsManager.java:507)
        at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.isLayoutAnimationEnabled(ReanimatedNativeHierarchyManager.java:191)
        at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:266)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:211)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:977)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 

```

## Snack or minimal code example
https://github.com/mwegener-com/test2

## Package versions
- React Native: 0.64.3
- React Native Reanimated: 2.3.0
- Expo: 43.0.4

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by mwegener-com** [comment]
Flipper gives following error in my productive app, where I have the same issue:

```
FATAL EXCEPTION: main
Process: com.mwegener.cabernetco, PID: 5453
java.lang.IllegalStateException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
	at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:387)
	at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:394)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:33)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
	at com.swmansion.reanimated.layoutReanimation.AnimationsManager.isLayoutAnimationEnabled(AnimationsManager.java:507)
	at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.isLayoutAnimationEnabled(ReanimatedNativeHierarchyManager.java:191)
	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:266)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:211)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:977)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
	... 7 more

```

**Comment by johnf** [comment]
I started seing this today after upgrading from 2.2.4 to 2.3.0
This is on a CRA app.
I tried clean:android and rebuild which didn't help

Rolling back to 2.2.4 removed the issue.

I tested some other versions
* 2.2.4 - OK
* 2.3.0-beta.4 - BAD
* 2.3.0 - BAD

**Comment by togonow** [comment]
Having the same issue, was on 2.3.0-beta-2 upgraded to 2.3.0 didn't get resolved, will try to roll back to 2.2.4 now

**Comment by togonow** [comment]
> Having the same issue, was on 2.3.0-beta-2 upgraded to 2.3.0 didn't get resolved, will try to roll back to 2.2.4 now

bummer, even 2.2.4 doesn't work

**Comment by AnOptimistSeePessimist** [comment]
are you sure you roll back to 2.2.4

**Comment by togonow** [comment]
so turned out i didn't follow the setup for android as follows:
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/
and
https://github.com/software-mansion-labs/reanimated-2-playground/pull/8/commits/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8
now works on 2.3.0

**Comment by manoj-clix** [comment]
> I started seing this today after upgrading from 2.2.4 to 2.3.0 This is on a CRA app. I tried clean:android and rebuild which didn't help
> 
> Rolling back to 2.2.4 removed the issue.
> 
> I tested some other versions
> 
> * 2.2.4 - OK
> * 2.3.0-beta.4 - BAD
> * 2.3.0 - BAD

thank you @johnf for your findings.

**Comment by musadiq123** [comment]
@togonow Thank save my day

work for me few changes
https://github.com/software-mansion-labs/reanimated-2-playground/commit/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8

**Comment by archeraghi** [comment]
I am facing the same problem and did not do any updates. I am freaking out!!!!!! What did you guys roll back and how?

**Comment by seetamdivkar** [comment]
Thanks to @togonow  Saved me. 
[software-mansion-labs/reanimated-2-playground@71642db](https://github.com/software-mansion-labs/reanimated-2-playground/commit/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8)

**Comment by musadiq123** [comment]
@archeraghi added this following files:

android/app/build.gradle

project.ext.react = [
     enableHermes: true,  // make false to true
 ]

android/app/src/main/java/com/reanimated2playground/MainApplication.java:

import com.facebook.react.bridge.JSIModulePackage;
import com.swmansion.reanimated.ReanimatedJSIModulePackage;

add this also 
@Override
         protected JSIModulePackage getJSIModulePackage() {
           return new ReanimatedJSIModulePackage(); // <- add
         }

find below screen shot for more clearance 
<img width="1282" alt="Screenshot 2021-12-08 at 4 54 28 PM" src="https://user-images.githubusercontent.com/39898245/145201034-e06c996b-b9f9-4ea4-9aee-511a9c3ae747.png">

**Comment by piaskowyk** [comment]
Hello! Unfortunately, Expo SDK 43 does not support Reanimated 2.3.0 yet as it comes with brand new native code for layout animations etc. Hopefully, it will be included in Expo SDK 44 coming soon!

**Comment by mwegener-com** [comment]
> Hello! Unfortunately, Expo SDK 43 does not support Reanimated 2.3.0 yet as it comes with brand new native code for layout animations etc. Hopefully, it will be included in Expo SDK 44 coming soon!

Thanks. What about expo bare workflow (dev client)?

**Comment by Kudo** [comment]
i can confirm there's some compatible issue between expo-dev-client and reanimated 2.3.0 (but not expo sdk 43 project without dev-client). i'll report this issue internally. thanks @mwegener-com!

**Comment by mwegener-com** [comment]
@Kudo thanks! That's the error I get with dev client: https://github.com/software-mansion/react-native-reanimated/pull/2690#issuecomment-988839751

Could you open up this issue again and let me know if its fixed?

**Comment by Kudo** [comment]
@mwegener-com i'm sorry i cannot reopen this issue because this is reanimated repo. i think https://github.com/expo/expo/issues/15056 may related and good enough to track down the dev-client issue.

**Comment by shukla795** [comment]
> @togonow Thank save my day
> 
> work for me few changes [software-mansion-labs/reanimated-2-playground@71642db](https://github.com/software-mansion-labs/reanimated-2-playground/commit/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8)
@musadiq123  Thanks for save my day.

**Comment by johnf** [comment]
@piaskowyk Can you please reopen. I'm seeing this same problem and am not using expo. I'm using React Native CLI

**Comment by shukla795** [comment]
Yes this time I reopen it . This is working fine...

**Comment by shukla795** [comment]
Yes this time I reopen it . This is working fine...

**Comment by BeeMargarida** [comment]
> @piaskowyk Can you please reopen. I'm seeing this same problem and am not using expo. I'm using React Native CLI

We are also using React Native CLI and we have the same problem

**Comment by chj-damon** [comment]
> so turned out i didn't follow the setup for android as follows: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/ and [software-mansion-labs/reanimated-2-playground@71642db](https://github.com/software-mansion-labs/reanimated-2-playground/commit/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8) now works on 2.3.0

this doesn't work for me. as I followed the setup since v2.2.4, but after upgrading to 2.3.0, it breaks down.

**Comment by rpenido** [comment]
> @piaskowyk Can you please reopen. I'm seeing this same problem and am not using expo. I'm using React Native CLI

I was having the same problem. I solved following the instalation steps in:
- https://reactnavigation.org/docs/drawer-navigator/
- https://reactnavigation.org/docs/getting-started
- https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

Using version 2.3.0

**Comment by kakajann** [comment]
Still having the problem, tried everything mentioned above. The error is

`AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.f.j()' on a null object reference`

**Comment by Kudo** [comment]
hi there! if someone could share a minimal reproducible example without expo. it would be helpful for troubleshooting.

**Comment by alexkey89** [comment]
I'm using react native cli (version: 0.66.4) and see the same issue after upgrading to reanimated 2.3.0. Only on android, it works on iOS.

**Comment by Terfender** [comment]
I tried. both 2.3.0 and 2.2.4.
Having this issue only on Android release mode.
Debugging mode works fine.

Any ideas?

**Comment by Terfender** [comment]
This was the solution for my case: https://github.com/software-mansion/react-native-reanimated/pull/2725

**Comment by cl3i550n** [comment]
### **Solved this problem!**
**1° - Turn on Hermes engine by editing** `android/app/build.gradle`
```
project.ext.react = [
  enableHermes: true  // <- here -- change false for true
]
```

**2° - Plug Reanimated in MainApplication.java**
`android\app\src\main\java\com\<yourProjectName>\MainApplication.java`

```
  import com.facebook.react.bridge.JSIModulePackage; // <- add this
  import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add this
  ...
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
  ...

      @Override
      protected String getJSMainModuleName() {
        return "index";
      }
// add more this "Override" below <----------------
      @Override 
      protected JSIModulePackage getJSIModulePackage() {
        return new ReanimatedJSIModulePackage(); // <- add
      }
    };
  ...
```

### **Save all and rebuild** 
( Android is: `npx react-native run-android` )

**My package.json**
- "@react-navigation/drawer": "^6.1.8"
- "@react-navigation/native": "^6.0.6"
- "@react-navigation/native-stack": "^6.2.5"
- "react-native": "0.66.4"
- "react-native-gesture-handler": "^2.1.0"

**Comment by Glazzes** [comment]
I'm working in a bare managed workflow with the expo (v 43.0.4) package installed and reanimated 2.3.0 and i'm getting the same message as OP

**Comment by MeghanaChandrashekariah** [comment]
> @archeraghi added this following files:
> 
> android/app/build.gradle
> 
> project.ext.react = [ enableHermes: true, // make false to true ]
> 
> android/app/src/main/java/com/reanimated2playground/MainApplication.java:
> 
> import com.facebook.react.bridge.JSIModulePackage; import com.swmansion.reanimated.ReanimatedJSIModulePackage;
> 
> add this also @OverRide protected JSIModulePackage getJSIModulePackage() { return new ReanimatedJSIModulePackage(); // <- add }
> 
> find below screen shot for more clearance <img alt="Screenshot 2021-12-08 at 4 54 28 PM" width="1282" src="https://user-images.githubusercontent.com/39898245/145201034-e06c996b-b9f9-4ea4-9aee-511a9c3ae747.png">

This Worked for me. Thank you very much 🙏

**Comment by princebhatia09** [comment]
> I started seing this today after upgrading from 2.2.4 to 2.3.0 This is on a CRA app. I tried clean:android and rebuild which didn't help
> 
> Rolling back to 2.2.4 removed the issue.
> 
> I tested some other versions
> 
> * 2.2.4 - OK
> * 2.3.0-beta.4 - BAD
> * 2.3.0 - BAD

saved my 6 hours thank you so much

**Comment by kanzitelli** [comment]
Hi @Kudo! I am facing the same issue while updating [rnn-starter](https://github.com/kanzitelli/rnn-starter) and it has started happening after updating reanimated to 2.3.0. So here is a minimal reproducible example without expo (using RNN) -- [link](https://github.com/kanzitelli/rnn-starter/tree/packages-update).

In my case, it happens when I try to hot reload the app or restart it manually using react-native-restart.

**Comment by husseinAbdulnabi** [comment]
> This was the solution for my case: #2725

i can confirm, this solved my issue, it was happening only on release builds.

**Comment by partiellkorrekt** [comment]
I am still having this issue on Android 5. On newer Android-Versions it's working fine.

I have made sure to follow the installation instructions closely and I have disabled pro guard, but that doesn't change anything. Downgrading is also not an option since there are critical bugs in lower versions too.

**Comment by jshinrock** [comment]
I'm not sure this should be closed. After 8ish hours of extensive testing, I can confirm the following outcomes:

- reanimated 2.3.1 (with the proguard fix) WORKS on android the FIRST time you load the application
- after an update (codepush, in my case) the error here occurs

downgrading to 2.2.4 solves the issues because, well, there are no layout animations in 2.2.4, which is one of the reasons I wanted to upgrade in the first place.

Looking forward to being able to utilize the full improvements for 2.3.x when this is stable!

**Comment by jshinrock** [comment]
I should note that during my testing, it's fairly easy to break ANY version of reanimated2 with codepush updates (only tested Android so far), depending on how you are rendering/tearing down components. There are workarounds, but they all feel very fragile.

**Comment by nassim99** [comment]
I can confirm this issue still exists.
The app crash at start in a Release Mode, on Debug there is no problem.

This has fixed the issue for me:
> This was the solution for my case: #2725

**Comment by Goostavo** [comment]
As @partiellkorrekt tested.
It's working debug and release on newer android versions, but is crashing both debug and release on Android 5.

![image](https://user-images.githubusercontent.com/308200/146820603-352d3f41-e5e9-46b9-b728-1d5603859fd4.png)

**Comment by Mootassam** [comment]
. So just remove this package and install “react-native-reanimated”: “^1.13.2”. Now Your error should be solved.

**Comment by cl3i550n** [comment]
> ### **Solved this problem!**
> **1° - Turn on Hermes engine by editing** `android/app/build.gradle`
> ```
> project.ext.react = [
>   enableHermes: true  // <- here -- change false for true
> ]
> ```
> 
> **2° - Plug Reanimated in MainApplication.java**
> `android\app\src\main\java\com\<yourProjectName>\MainApplication.java`
> 
> ```
>   import com.facebook.react.bridge.JSIModulePackage; // <- add this
>   import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add this
>   ...
>   private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
>   ...
> 
>       @Override
>       protected String getJSMainModuleName() {
>         return "index";
>       }
> // add more this "Override" below <----------------
>       @Override 
>       protected JSIModulePackage getJSIModulePackage() {
>         return new ReanimatedJSIModulePackage(); // <- add
>       }
>     };
>   ...
> ```
> 
> ### AFTER ALL PROCESS
> 
> **React Navigation Docs**
> To finalize installation of **react-native-gesture-handler**, add the following at the top (make sure it's at the top and there's nothing else before it) of your entry file, such as `index.js` or `App.js`
> 
> `import 'react-native-gesture-handler';`
> 
> ### **Save all and rebuild** 
> ( Android is: `npx react-native run-android` )
> 
> **My package.json**
> - "@react-navigation/drawer": "^6.1.8"
> - "@react-navigation/native": "^6.0.6"
> - "@react-navigation/native-stack": "^6.2.5"
> - "react-native": "0.66.4"
> - "react-native-gesture-handler": "^2.1.0"

Guys!!! SEE MT POST for this issue... Works Fine for lasted dependencies!

**Comment by jshinrock** [comment]
> Guys!!! SEE MT POST for this issue... Works Fine for lasted dependencies!

As noted, this works just fine for an app booting up. The trouble for me is when an app-teardown event occurs, like a javascript reset (due to a codepush update in my case). That's when the error happens. 

If I didn't need that part of my process to work, I would agree that this is solved.

**Comment by cl3i550n** [comment]
> 
> > Guys!!! SEE MT POST for this issue... Works Fine for lasted dependencies!
> 
> As noted, this works just fine for an app booting up. The trouble for me is when an app-teardown event occurs, like a javascript reset (due to a codepush update in my case). That's when the error happens. 
> 
> If I didn't need that part of my process to work, I would agree that this is solved.

Your case is very specific... Too bad it doesn't work this method

**Comment by FredHSQ** [comment]
> I used this method and it worked (it seems) but know just as the app finish bundle it crashes with no log error, no red screen, nothing indicating what is the cause. If i try to bundle it a few more times the emulator says that the app keeps crashing. Happened to anyone?

**Comment by dpyeates** [comment]
For those of you seeing this in release builds only, try adding the following to your pro guard-rules file:

-keep class com.swmansion.reanimated.** { *; }

**Comment by wdmhouston** [comment]
OMG, I hit this issue in my day-1 React native learning!  It took me half day to search online and fixed after reading this thread.

**Comment by fanzhiri** [comment]
> > ### **Solved this problem!**
> > **1° - Turn on Hermes engine by editing** `android/app/build.gradle`
> > ```
> > project.ext.react = [
> >   enableHermes: true  // <- here -- change false for true
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **2° - Plug Reanimated in MainApplication.java**
> > `android\app\src\main\java\com\<yourProjectName>\MainApplication.java`
> > ```
> >   import com.facebook.react.bridge.JSIModulePackage; // <- add this
> >   import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add this
> >   ...
> >   private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
> >   ...
> > 
> >       @Override
> >       protected String getJSMainModuleName() {
> >         return "index";
> >       }
> > // add more this "Override" below <----------------
> >       @Override 
> >       protected JSIModulePackage getJSIModulePackage() {
> >         return new ReanimatedJSIModulePackage(); // <- add
> >       }
> >     };
> >   ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### AFTER ALL PROCESS
> > **React Navigation Docs**
> > To finalize installation of **react-native-gesture-handler**, add the following at the top (make sure it's at the top and there's nothing else before it) of your entry file, such as `index.js` or `App.js`
> > `import 'react-native-gesture-handler';`
> > ### **Save all and rebuild**
> > ( Android is: `npx react-native run-android` )
> > **My package.json**
> > 
> > * "@react-navigation/drawer": "^6.1.8"
> > * "@react-navigation/native": "^6.0.6"
> > * "@react-navigation/native-stack": "^6.2.5"
> > * "react-native": "0.66.4"
> > * "react-native-gesture-handler": "^2.1.0"
> 
> Guys!!! SEE MT POST for this issue... Works Fine for lasted dependencies!

not work well at 2.3.1

**Comment by trickyc0d3r** [comment]
> As @partiellkorrekt tested. It's working debug and release on newer android versions, but is crashing both debug and release on Android 5.
> 
> Reverting to 2.2.4 fixed the issue
> 
> ![image](https://user-images.githubusercontent.com/308200/146820603-352d3f41-e5e9-46b9-b728-1d5603859fd4.png)

NOPE! I'm still having this issue on 2.2.4

**Comment by nassim99** [comment]
> > As @partiellkorrekt tested. It's working debug and release on newer android versions, but is crashing both debug and release on Android 5.
> > Reverting to 2.2.4 fixed the issue
> > ![image](https://user-images.githubusercontent.com/308200/146820603-352d3f41-e5e9-46b9-b728-1d5603859fd4.png)
> 
> NOPE! I'm still having this issue on 2.2.4

check your package.json file
make sure you have
`"react-native-reanimated": "2.2.4",`
Notice that there is no "^" !!!

**Comment by RaguRam1991** [comment]
> `import 'react-native-gesture-handler';`

thanks @nassim99 this worked for me. 

i removed reanimated package, installed with 2.2.4 and it worked. thank you

**Comment by yanush** [comment]
Is someone working on a fix for 2.3* versions?

**Comment by kanzitelli** [comment]
Hey @piaskowyk @Kudo 👋

As I can see from the logs, the issue lies in `AnimationsManager.java` on [the 507-th line](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java#L507) where `mNativeMethodsHolder` might be `null`.

Also it shows that the call of `isLayoutAnimationEnabled()` is coming from `ReaLayoutAnimator` interface on `ReanimatedNativeHierarchyManager.java` [191-st line](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java#L191). This interface is used in the same file on [355-th line](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java#L355). And it seems that `mReaLayoutAnimator` (that is casted to `ReaLayoutAnimator` interface) might be `null` for some reason. Maybe we can just add a check on `null` there?
I've seen it's being used in two more places: [236-th line](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java#L236) and [266-th line](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java#L266)

It's just some investigations and thoughts. I'd be glad to play around with that but got lost when I've been trying to build `aar`s for Android and publishing the package and couldn't find contribution guide.

**Comment by piaskowyk** [comment]
ok, I will check it again

**Comment by kanzitelli** [comment]
@piaskowyk thanks! will be glad to help with testing!

Happy New Year!

**Comment by learningnoobi** [comment]
this issue is making me loose sleep .

**Comment by yanush** [comment]
> this issue is making me loose sleep .

me too. I have ~100 crashes per day cause of this issue :(

**Comment by dngconsulting** [comment]
Same here :(

**Comment by SaeedZhiany** [comment]
FYI @piaskowyk, recently I'm experiencing it on android API 28 too

**Comment by learningnoobi** [comment]
> > this issue is making me loose sleep .
> 
> me too. I have ~100 crashes per day cause of this issue :(

I have solved this by using reanimated 2.2.4 and adding 


> > > **1° - Turn on Hermes engine by editing** `android/app/build.gradle`
> > > ```
> > > project.ext.react = [
> > >   enableHermes: true  // <- here -- change false for true
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **2° - Plug Reanimated in MainApplication.java**
> > > `android\app\src\main\java\com\<yourProjectName>\MainApplication.java`
> > > ```
> > >   import com.facebook.react.bridge.JSIModulePackage; // <- add this
> > >   import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add this
> > >   ...
> > >   private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
> > >   ...
> > > 
> > >       @Override
> > >       protected String getJSMainModuleName() {
> > >         return "index";
> > >       }
> > > // add more this "Override" below <----------------
> > >       @Override 
> > >       protected JSIModulePackage getJSIModulePackage() {
> > >         return new ReanimatedJSIModulePackage(); // <- add
> > >       }
> > >     };
> > >   ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >

**Comment by SaeedZhiany** [comment]
@learningnoobi downgrading is not an ideal option, because we all did upgrade to the latest version for fixing the previous bugs and also using the new LayoutAnimation feature.

**Comment by learningnoobi** [comment]
@SaeedZhiany I only needed reanimated for drawer navigation . So , I downgraded cause this issue was taking too much time

**Comment by Sidhum27** [comment]
"react-native-reanimated": "2.2.4",  downgrade to  "react-native-reanimated": "^2.3.1" that will solve this issue

**Comment by SaeedZhiany** [comment]
> "react-native-reanimated": "2.3.1", downgrade to "react-native-reanimated": "^2.2.4" that will solve this issue

This solution has been commented on many times by the others on this thread and there is no need for everyone to repeat that.

@mwegener-com 

please update your first comment on this thread and mention that this issue occurs on version 2.3.0 and above and it's OK on lower versions. this might prevent others from commenting on the same downgrading solution and keep this thread focused on the main problem.

**Comment by yanush** [comment]
Does react-native-reanimated 2.2.4 work well with react-native-gesture-handler 2.1.0?

**Comment by stephenlaughton** [comment]
We are experiencing a ton of crashes on Android because of this when we upgraded to Expo 44. Has anyone got an Expo 44 Android app in production where they successfully worked around this?

**Comment by romanonthego** [comment]
can confirm, we receive crash reports from android devices with this bug, had to rollback to 2.2.4
It seems it does not appear always, hard to pinpoint exactly why.

**Comment by ryan-barker-zefr** [comment]
I can reproduce this 100% of the time using Firebase Robo test, ALE-L23, API Level 21 using Expo 44 with 2.3.1
Confirmed rollback to 2.2.4 works as expected.

Hope this helps with fixing this issue.

**Comment by stephenlaughton** [comment]
@piaskowyk any ideas on this issue? If downgrading to `2.2.4` isn't an option, are there any other options to use `2.3.1` with Expo 44?

**Comment by jrdnbrj** [comment]
Version 2.2.4 solves my problem.

**Comment by harsh5099** [comment]
> I started seing this today after upgrading from 2.2.4 to 2.3.0 This is on a CRA app. I tried clean:android and rebuild which didn't help
> 
> Rolling back to 2.2.4 removed the issue.
> 
> I tested some other versions
> 
> * 2.2.4 - OK
> * 2.3.0-beta.4 - BAD
> * 2.3.0 - BAD

Thanks bro it work in my case.

**Comment by Raman-3r** [comment]
i also get this error "react-native-reanimated": "^2.3.1 in that, please suggest me how to resolve it.

**Comment by pushpender-singh-ap** [comment]
"react-native-reanimated": "^2.3.1"
"react": "17.0.2",
"react-native": "0.66.4",

<img width="951" alt="Screenshot 2022-01-17 at 9 38 56 PM" src="https://user-images.githubusercontent.com/73298854/149804084-94806457-d7de-411e-917d-6029530ee53a.png">
<img width="946" alt="Screenshot 2022-01-17 at 9 39 13 PM" src="https://user-images.githubusercontent.com/73298854/149804102-176c1821-c189-4604-b703-aa7be94709ac.png">


```
Fatal Exception: java.lang.IllegalStateException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
       at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:425)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:775)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Raman-3r** [comment]
thanks

**Comment by FadiAboMsalam** [comment]
@pushpender-singh-ap I had the same environment and the same issue what weirdly solve the issue for me is the **order of import** in MainApplication.java
and by adding this rule to proguard-rules.pro

`-keep class com.swmansion.reanimated.** { *; }
`

please have a look at the screenshot below 
![Screen Shot 2022-01-18 at 11 09 39](https://user-images.githubusercontent.com/12826829/149906740-29a64066-3274-400a-9488-14e8a06f17ed.png)

**Comment by dishantwalia** [comment]
Fixed by following installation guide:  https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

**Comment by partiellkorrekt** [comment]
This installation guide does not fix the problem on Android 5. But this pull-request seems to fix the problem for me: https://github.com/software-mansion/react-native-reanimated/pull/2847

The reason is, that the class "ReanimatedNativeHierarchyManager" uses the feature "accessFlags" that doesn't exist on Android 5. That will raise the exception mentioned in the pull-request and prevent the field "mReaLayoutAnimator" from being initialized.

The main-branch version of this library will only log this error but still set layoutAnimationEnabled to true. So during runtime this library will try to call "mReaLayoutAnimator" which is null. That is the reason for this NullPointerException that crashes the App.

I have compiled the package from the pull-request and I can confirm that now it's working stable again.

In case you want to compile that package yourself on macOS, I found that you have to set the environment variable "ANDROID_SDK_ROOT" and install "wget" before you can run "createNPMPackage.sh" from the repository.

**Comment by jeanbispo** [comment]
I'm solved with
`"react-native-reanimated": "2.2.4",`
and follow this guide: 
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation

**Comment by sam-houle1** [comment]
This installation guide does not fix the problem for me, after upgrading react native to 0.66.4, we started encountering this issue, no matter which version I switch to I have the problem. Anyone has a way to fix this issue, this is a big problem for us, everytime the app refresh the app crash.

**Comment by mu-zzi** [comment]
> so turned out i didn't follow the setup for android as follows: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/ and [software-mansion-labs/reanimated-2-playground@71642db](https://github.com/software-mansion-labs/reanimated-2-playground/commit/71642dbe7bd96eb41df5b9f59d661ab15f6fc3f8) now works on 2.3.0

Thanks a lot. This helped me. Now I'm even running react-native-reanimated on 2.3.1 without any issue.
To be clear: I have react 17.0.2 and react-native 0.66.4.

**Comment by partiellkorrekt** [comment]
You need to install the version from this branch (for now): https://github.com/software-mansion/react-native-reanimated/pull/2847

A pre-built version is available here: https://github.com/giautm/react-native-reanimated/actions/runs/1713641466

@mu-zzi Did you also try running your app on Android 5? The installation-guide only fixes the problem for Android > 5.

**Comment by yasuohasegawa** [comment]
Yeah, This issue happened only in the release build. The debug build works OK with 2.3.0.
2.2.4 with React Native v0.67.1 worked on Pixel3a OS12. I hope we will get the fixed version soon.

**Comment by ProMasoud** [comment]
This worked for me in react-native@0.67.0

https://stackoverflow.com/a/70337772/5635189

**Comment by mu-zzi** [comment]
> You need to install the version from this branch (for now): #2847
> 
> A pre-built version is available here: https://github.com/giautm/react-native-reanimated/actions/runs/1713641466
> 
> @mu-zzi Did you also try running your app on Android 5? The installation-guide only fixes the problem for Android > 5.

I have to confess, no, not on Android 5.

**Comment by piaskowyk** [comment]
Hey, this issue is resolved by: https://github.com/software-mansion/react-native-reanimated/pull/2847 I will release it next week.

**Comment by sergeymild** [comment]
on version 2.3.1 still exists this issue

**Comment by apurv-6** [comment]
still exist , any update in package upgrade , the library is awesome but effecting our crash metrics please help !

**Comment by partiellkorrekt** [comment]
Version 2.3.1 was always broken. Until there is a new version, you can install a custom built branch. See https://github.com/software-mansion/react-native-reanimated/issues/2702#issuecomment-1018415367

**Comment by SamiChab** [comment]
You can install the https://github.com/software-mansion/react-native-reanimated/pull/2847 PR this way:
`yarn add software-mansion/react-native-reanimated#2847/head`
It did the trick for me

**Comment by mozadeh** [comment]
When I use the latest PR i get this `Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-reanimated.
     Required by:
         project :app
      > No matching configuration of project :react-native-reanimated was found. `

**Comment by apurv-6** [comment]
@SamiChab  I tried you way of doing this , but my android is not able to link with com.swamsion.reanimated , though in my node modules I have got the code from the fixed branch , can see the fixes 

> You can install the #2847 PR this way: `yarn add software-mansion/react-native-reanimated#2847/head` It did the trick for me

**Comment by dittmarconsulting** [comment]
Hi all, 

I'm using RN CLI and have the same issue:

```
02-16 20:16:28.631 15459 15459 E AndroidRuntime: FATAL EXCEPTION: main
02-16 20:16:28.631 15459 15459 E AndroidRuntime: Process: com.ampjarapp, PID: 15459
02-16 20:16:28.631 15459 15459 E AndroidRuntime: java.lang.IllegalStateException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
```

Here my setup

```
"react": "^17.0.2",
"react-native": "^0.66.3",
"react-native-reanimated": "2.3.0"

Testing on physical Android phone - Samsung SM-G950N
```

I tried to install the workaround `yarn add software-mansion/react-native-reanimated#2847/head` but now it says

```
* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> /<my project>/node_modules/react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
```

I had a look into that directory and `react-native` is indeed missing. 
![Screen Shot 2022-02-17 at 10 40 26 am](https://user-images.githubusercontent.com/19203201/154376018-c5f41fe2-ed4c-45be-a710-a0a4b10980bb.png)

Is there anything else I can do right now?

**Comment by ybonnetain** [comment]
You might get this crash when the destination screen itself is not able to render correctly.

eg.

I have a master / detail flow where the detail is a PdfView that requires a local URI for the fetched PDF.
Turns out I used a bad URL to fetch the data and the byte-array I was feeding the PdfView was garbage.
As a result the destination screen cannot mount and it seems that subsequently REA has nothing to work with (your view hierarchy is broken anyway)

```
> Screen 1 -> (push) -> Screen 2 -> (Boom)
> --------------------> REA exception !
```

This was the problem for me,
I hope this might help after strictly following installation guide.

**Comment by OnurVar** [comment]
> Yeah, This issue happened only in the release build. The debug build works OK with 2.3.0.
> 2.2.4 with React Native v0.67.1 worked on Pixel3a OS12. I hope we will get the fixed version soon.

Please check your `proguad-rules.pro` file

```
# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }
```

**Comment by dittmarconsulting** [comment]
The same happened for me in debug mode. Mainly when I switch navigation stacks. It only occurs on Android though.

I use 2.3.0 now but when I upgraded `reanimated` to 2.4.1, I get this error https://github.com/software-mansion/react-native-reanimated/issues/3008

The app is now on the Play Store. I already saw 5 crashes. I don't know what to do.

**Comment by cskeppstedt** [comment]
> progu

To anyone who needs to modify proguard rules in a managed expo project: you can use a config plugin. I've created a gist with a working solution: https://gist.github.com/cskeppstedt/d44f043d7c621c4c800a66c9656b1d87

**Comment by lqze** [comment]
This issue should be re-opened.

**Comment by MateuszRostkowski** [comment]
@cskeppstedt Your solution doesn't work for me, but this works perfectly:

https://gist.github.com/MateuszRostkowski/6aa018cd3294ecec50481475503e4074 (I have modified your code and run in production app)

For anyone strugling with this, for version 2.3.1 you need to also modify `MainApplication.java` file. Reanimated have already 2.6 version and expo is still using 2.3.1. Let's hope that in next expo sdk upgrade we will don't need to change native files.

**Comment by ScreamZ** [comment]
Thanks @MateuszRostkowski, care the installation in the gist is not well named, its useReanimated

**Comment by derekstavis** [comment]
I've been experiencing this crash in both production and development builds of my app. No Proguard. Using Expo (with EAS) but also local builds with `expo run:android` (which essentially generate an `android`) directory. Versions are as follows:

```
    "react-native": "0.64.3",
    "react-native-reanimated": "~2.3.1",
    "react-native-gesture-handler": "~2.1.0",
    "expo": "~44.0.0",
```

I tried to isolate the problem in the userland and confirmed the following:

1. Replacing the main screen with an empty `<View />` still triggers the crash, so it's not a rendering issue
2. Removing anything that imports `reanimated` still triggers the crash, so it's not being triggered from JS

Here are the patterns I could derive from my investigations so far:

1. It does not crash on Expo EAS development clients when launching from the launcher
4. It does not crash on Expo locally compiled development clients when launching from the launcher
5. It DOES crash when bypassing the launcher, e.g.: `expo run:android` 

I also had the problem mentioned in [this comment](https://github.com/software-mansion/react-native-reanimated/issues/2702#issuecomment-1047499739) when trying to upgrade Reanimated.

**Comment by MateuszRostkowski** [comment]
> Thanks @MateuszRostkowski, care the installation in the gist is not well named, its useReanimated

@ScreamZ I've fixed it, thanks.
