### ISSUE TITLE
After upgrade to 2.4.1 types for style prop (Animated.View) are incompatible with Animated.Value

### ISSUE THREAD

**Issue by ahanusek** [software-mansion/react-native-reanimated#2968]
## Description

After upgrade from 2.2.4 to the latest version (2.4.1) I'm getting many TypeScript errors in all places where I use Animated.View with Animated.Value from Reanimated v1.

### Expected behavior

Types shouldn't throw errors to valid usage of style prop.

### Actual behavior & steps to reproduce

```
 <Animated.View
            style={{
                opacity: animation.current,
            }}
        >
        
        </Animated.View>
```

That's throw error but refactored to

```
 <Animated.View
            style={[{
                opacity: animation.current,
            }]}
        >
        
        </Animated.View>
```

works fine

## Snack or minimal code example

```
const Component = () => {
 
 const animation = useRef(new ReAnimated.Value(Dimensions.get('window').height));}
 ....
 
 <Animated.View
            style={{
                left: 0,
                top: animation.current,  <----- this line throw TS error after upgrade
                right: 0,
                bottom: trueBottom * -1,
                backgroundColor: colors.GRAY_50,
                zIndex: 99,
            }}
        >
        
         ......
        </Animated.View>

```

TS Error:

TS2769: No overload matches this call.<br/>Overload 1 of 2, '(props: AnimateProps&lt;ViewProps&gt; | Readonly&lt;AnimateProps&lt;ViewProps&gt;&gt;): View', gave the following error.<br/>Type '{ position: &quot;absolute&quot; | &quot;relative&quot;; display: &quot;none&quot; | &quot;flex&quot;; left: number; top: ReAnimated.Value&lt;number&gt;; right: number; bottom: number; backgroundColor: string; zIndex: number; }' is not assignable to type '((false | ViewStyle | RegisteredStyle&lt;ViewStyle&gt; | RecursiveArray&lt;Falsy | ViewStyle | RegisteredStyle&lt;ViewStyle&gt;&gt; | AnimatedNode&lt;...&gt;) &amp; (false | ... 4 more ... | RecursiveArray&lt;...&gt;)) | null | undefined'.<br/>Type '{ position: &quot;absolute&quot; | &quot;relative&quot;; display: &quot;none&quot; | &quot;flex&quot;; left: number; top: ReAnimated.Value&lt;number&gt;; right: number; bottom: number; backgroundColor: string; zIndex: number; }' is not assignable to type 'undefined'.<br/>Overload 2 of 2, '(props: AnimateProps&lt;ViewProps&gt;, context: any): View', gave the following error.<br/>Type '{ position: &quot;absolute&quot; | &quot;relative&quot;; display: &quot;none&quot; | &quot;flex&quot;; left: number; top: ReAnimated.Value&lt;number&gt;; right: number; bottom: number; backgroundColor: string; zIndex: number; }' is not assignable to type '((false | ViewStyle | RegisteredStyle&lt;ViewStyle&gt; | RecursiveArray&lt;Falsy | ViewStyle | RegisteredStyle&lt;ViewStyle&gt;&gt; | AnimatedNode&lt;...&gt;) &amp; (false | ... 4 more ... | RecursiveArray&lt;...&gt;)) | null | undefined'.<br/>Type '{ position: &quot;absolute&quot; | &quot;relative&quot;; display: &quot;none&quot; | &quot;flex&quot;; left: number; top: ReAnimated.Value&lt;number&gt;; right: number; bottom: number; backgroundColor: string; zIndex: number; }' is not assignable to type 'undefined'.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.66.4      |
| react-native-reanimated              |   2.4.1       |
| TypeScript              |   4.5.4       |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |         |

## Affected platforms

- [X] Android
- [X] iOS
- [ ] Web

**Comment by james-zhan-apt** [comment]
same here

**Comment by andrecrimb** [comment]
Same issue

**Comment by andrecrimb** [comment]
As @ahanusek mentioned, wrapping the style object around an array solves the issue.

**Comment by pke** [comment]
Will this be fixed @andrecrimb?

**Comment by piaskowyk** [comment]
Should be resolved with: https://github.com/software-mansion/react-native-reanimated/pull/3098 🎉

**Comment by oblador** [comment]
I can confirm that this issue persists with linked fix, and think this issue should be re-opened @piaskowyk

**Comment by magrinj** [comment]
Still present on `2.8.0`

**Comment by magrinj** [comment]
@piaskowyk After some digging, it seems to be related to the commit between version `2.4.0` and `2.4.1` ([7d75b634a6a108a49e0b02f70b80de06230ea919](https://github.com/software-mansion/react-native-reanimated/commit/7d75b634a6a108a49e0b02f70b80de06230ea919)) that change the type of `AnimatedProps`.

If I reverse the following change, everything seems to works fine.

**Comment by magrinj** [comment]
@piaskowyk I've fixed the issue in the following PR #3301 
@alois-beto @ahanusek
