### ISSUE TITLE
Issues while debugging with chrome

### ISSUE THREAD

**Issue by cglacet** [software-mansion/react-native-reanimated#2989]
## Description

The same code behaves differently when debug mode is active (Android). I haven't tested iOS yet. 
The debugger is `React Native Debugger 0.12.1`.

The example is based on [reanimated-2-playground](https://github.com/software-mansion-labs/reanimated-2-playground), where I simply: 

* changed the app name
* updated to react-native `0.67.2` 
* updated to reanimated `2.4.1` 
* and added [@react-navigation/drawer](https://github.com/react-navigation/react-navigation/tree/main/packages/drawer) and [@react-navigation/native](https://www.npmjs.com/package/@react-navigation/native).

The `App` code simply is a mix of the [navigation drawer MWE](https://reactnavigation.org/docs/drawer-based-navigation/#minimal-example-of-drawer-based-navigation) and the reanimated2 initial playground content.

### Clean up step

```
rm -rf node_modules yarn.lock && yarn install && cd android && ./gradlew clean && cd - && yarn android
```

I also removed `~/.gradle` completely several times to make sure nothing strange happens here.

### Expected behavior

In both normal and debug mode, the app should render this:

<img width="384" alt="Screenshot 2022-02-10 at 12 32 34" src="https://user-images.githubusercontent.com/28622118/153400689-507d95e4-f0fb-4a24-bef1-b0feea6790a1.png">

and this: 

<img width="382" alt="Screenshot 2022-02-10 at 12 33 05" src="https://user-images.githubusercontent.com/28622118/153400759-138c4871-74a2-4e84-a806-9ac7fc2e19f9.png">

In the original playground screen, I expect animations to happen if I click toggle

### Actual behavior & steps to reproduce

Saddly, when the debugger is active, I get a white screen.

If I remove the Drawer navigator, the app shows as expected BUT there are no animation when I click "TOGGLE", the black bar blinks to its next width directly.

The code for this second test is basically the playground one:

```
export default function App() {
  return <AnimatedStyleUpdateExample />;
}
```

## Snack or minimal code example

This [repo](https://github.com/cglacet/reanimated2-issue-demo):

```
git clone https://github.com/cglacet/reanimated2-issue-demo.git
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.67.2     |
| react-native-reanimated              |     2.4.1    |
| NodeJS                               |   16.13.0      |
| Java                                 |      11.0.11 2021-04-20   |
| Gradle                               |      7.2   |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

### Device used

* Emulator (qemu) with a Pixel 5 (api 30)

**Comment by sanjay628** [comment]
Hello Team ,

I am facing multiple issue like debugger is not working , on android when app is in debug mode it works but in release it wont  work with updates as well as older version are also having the same issue now.

 "@react-navigation/drawer": "^6.1.8",

**Comment by fatlinesofcode** [comment]
same issue here in ios simulator, 

name | version
-- | --
react-native | 0.64.2
react-native-reanimated | 2.4.1
NodeJS | 14.15.4
Xcode 13.2.1

**Comment by tomgreco** [comment]
Same issue with latest

**Comment by Soliy0u** [comment]
Same issue with react-native-animated 2.10.0. Working fine in normal but when the debugger is active, I get a white screen.
I have read in docs: https://docs.swmansion.com/react-native-reanimated/docs/
**Known problems and limitations
Reanimated 2 is in an early version. As we wanted to share it with the community as soon as we could, the library still has some rough edges and limitations that we plan to address soon. Unfortunately some of the limitations come from maturity of React Native's TurboModule architecture that Reanimated 2 relies on. As a consequence we won't be able to support older versions of React Native and some issues that we yet plan to resolve may require full support of TurboModules which is not yet available to the public.

Below we highlight some of the problems that we are aware of (in most of the cases we actively work on improving these):

**As the library uses JSI for synchronous native methods access, remote debugging is no longer possible. You can use Flipper for debugging your JS code, however connecting debugger to JS context which runs on the UI thread is not currently supported.**
I have try with Flipper but get more bugs: https://github.com/facebook/flipper/issues/4205.  Does anyone have a recommendation on how to fix these?

**Comment by mutablestudio** [comment]
The reanimated docs state that v2.x is compatible with Chrome Debugger aka React Native Debugger - https://docs.swmansion.com/react-native-reanimated/docs/next/guide/debugging/ - however I get similar issues with the app just freezing up on launch screen when enabling debugging. RN Debugger 0.13.0 with RN 0.68.5 and reanimated 2.13.0. Happens in iOS Simulator (iOS 14 Pro). Problem is gone when debugging is disabled or reanimated is reverted to `1.13.2`. Would be great if someone from reanimated team could look at this. With so many issues w v2 I did not want to update but there are now critical security issues identified in versions lower than 2.10.0 (ReDoS)

**Comment by mutablestudio** [comment]
UPDATE: for my specific issue with iOS, it was resolved by enabling Hermes in the pod file, then doing pod install. Without this the network requests to localhost:8081/debugger-proxy will be in pending state and never resolve (you can view this in the network tab of the chrome debugger). This also switched my debugger to Flipper. I could find no mention anywhere in any of the reanimated 2.x docs about whether Hermes is required or not.

**Comment by yangalav** [comment]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px;">same issue here on both ios simulator and android. Also seeing white screen on iOS. Not working for the debugger in Chrome nor the React Native Debugger. Had to downgrade to get my RN app to work and be debuggable.,</p><table role="table" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px; margin-bottom: 0px !important; display: block; width: max-content; max-width: 100%; overflow: auto;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><th style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);">name</th><th style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--color-border-default);">version</th></tr></thead><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);">react-native</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);">0.63.2</td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-subtle); border-top: 1px solid var(--color-border-muted);"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);">react-native-reanimated</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);">2.13.0</td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);">NodeJS</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default);">>=12.15.0</td></tr><tr style="box-sizing: border-box; background-color: var(--color-canvas-subtle); border-top: 1px solid var(--color-border-muted);"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-border-default); color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Xcode 14.2</td><br class="Apple-interchange-newline">

**Comment by szydlovsky** [comment]
Hey everyone, do the debugging issues persist on 3.x versions? I am doing a review of older issues and was wondering if any of you are still having problems. (And a small reminder that debugging with Flipper is deprecated since React Native 0.73).

**Comment by szydlovsky** [comment]
And a reminder that as of now, only chrome dev tools work with react-native debugging
