### ISSUE TITLE
[Web]ReferenceError: _frameTimestamp is not defined

### ISSUE THREAD

**Issue by alantoa** [software-mansion/react-native-reanimated#3355]
## Description
Get this error when upgrading `react-native-reanimated` to `v2.9.0+` on the web (`v2.8.0` works), it works fine on iOS and Android.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/37520667/177155113-bbd1e5dd-8fcc-41d3-84d9-95299bb6b01a.png">

### Expected behavior 

Works on the web.

### Actual behavior & steps to reproduce 

web not working when upgrading to `v2.9.0+`.

## Snack or minimal code example 

https://github.com/tamagui/starters/tree/main/next-expo-solito

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.68.2     |
| react-native-reanimated              |    2.9.1     |
| NodeJS                               |     16.15.1    |
| Xcode                                |     13.4.1      |
| Java                                 |         |
| Gradle                               |         |
| expo                                 |     45.0.2    |

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by zzph** [comment]
I'm also facing this issue, on 2.9.1 on web.

For example, in this repo (not minimal): https://github.com/tamagui/starters/tree/main/next-expo-solito

Has anyone found a solution?

**Comment by tpisto** [comment]
Same problem with simple react-native-web project with library version 2.9.1.

**Comment by mikevocalz** [comment]
> 

which file to be exact?

**Comment by mo-fouad** [comment]
had the same issue with V2.9 and had to downgrade to 2.8.

**Comment by WillenOLeal** [comment]
Having the same issue while using Next.js any updates on this?

**Comment by piaskowyk** [comment]
@WillenOLeal I fixed it, but this hasn't been released yet. I want to release the new version this week.

**Comment by azimgd** [comment]
Hey @piaskowyk. Can we get new version released please ?

**Comment by vbylen** [comment]
Hmm I'm on `3.0.0-rc.1` and still getting the `_frameTimestamp is not defined` error on web.

**Comment by ChronSyn** [comment]
I've been experiencing this recently too. My use-case was with Moti (on Expo SDK46) presence animation.

I've found that this issue seems to only happen in the built bundle, and not when running local dev (e.g. via `expo start --web`). The correct transpilation process is setup for moti and reanimated.

(Sorry for cross-promoting, but switching to https://legendapp.com/dev/motion/animate-presence/ on web solves my specific issue - might be useful for others, though this doesn't have the performance benefits of reanimated)

**Comment by dohomi** [comment]
I bumped into the issue as well on the latest 3.0.0-rc2. Is there a temporary solution for it?

**Comment by tpisto** [comment]
> I bumped into the issue as well on the latest 3.0.0-rc2. Is there a temporary solution for it?

Add window._frameTimestamp = null on top of the component file

**Comment by jesse-savary** [comment]
> I bumped into the issue as well on the latest 3.0.0-rc2. Is there a temporary solution for it?

Stick the following in `_app.tsx`:
```
if (process.browser) {
  // @ts-ignore
  window._frameTimestamp = null
}
```

**Comment by sunnylqm** [comment]
still not fixed on 2.11.0

**Comment by crutch12** [comment]
Bump

**Comment by bombillazo** [comment]
Bump

**Comment by JamesHemery** [comment]
Today on 2.12.0 with #3418 merged the problem is still present after building the application with Expo.

**Temp fix of @jesse-savary works:** 

> > I bumped into the issue as well on the latest 3.0.0-rc2. Is there a temporary solution for it?
> 
> Stick the following at the top of `_app.tsx`, outside the component definition:
> 
> ```
> // FIXME need reanimated update, see https://github.com/software-mansion/react-native-reanimated/issues/3355
> if (process.browser) {
>   // @ts-ignore
>   window._frameTimestamp = null
> }
> ```

**Comment by Ryanjso** [comment]
We're still having this issue

**Comment by pencilcheck** [comment]
Still having this issue

**Comment by prateem** [comment]
> Today on 2.12.0 with #3418 merged the problem is still present after building the application with Expo.
> 
> **Temp fix of @jesse-savary works:**
> 
> > > I bumped into the issue as well on the latest 3.0.0-rc2. Is there a temporary solution for it?
> > 
> > 
> > Stick the following at the top of `_app.tsx`, outside the component definition:
> > ```
> > // FIXME need reanimated update, see https://github.com/software-mansion/react-native-reanimated/issues/3355
> > if (process.browser) {
> >   // @ts-ignore
> >   window._frameTimestamp = null
> > }
> > ```

I get error `process is not defined`, am I missing something?

**Comment by Ryanjso** [comment]
> > Today on 2.12.0 with #3418 merged the problem is still present after building the application with Expo.
> > **Temp fix of @jesse-savary works:**
> > > > I bumped into the issue as well on the latest 3.0.0-rc2. Is there a temporary solution for it?
> > > 
> > > 
> > > Stick the following at the top of `_app.tsx`, outside the component definition:
> > > ```
> > > // FIXME need reanimated update, see https://github.com/software-mansion/react-native-reanimated/issues/3355
> > > if (process.browser) {
> > >   // @ts-ignore
> > >   window._frameTimestamp = null
> > > }
> > > ```
> 
> I get error `process is not defined`, am I missing something?

You need to let TS know that process exists. Create a file named global.d.ts and add the following to it:

```
declare namespace NodeJS {
    interface Process {
        browser: boolean
    }
}

```

**Comment by prateem** [comment]
> 
> You need to let TS know that process exists. Create a file named global.d.ts and add the following to it:
> 
> ```
> declare namespace NodeJS {
>     interface Process {
>         browser: boolean
>     }
> }
> ```

Thanks for the quick reply! I've tried this and I still get this error in the console:

```
Uncaught ReferenceError: process is not defined
    at ./App.tsx (App.tsx:9:1)
    at __webpack_require__ (bootstrap:24:1)
 ```
 
 for environment context I am using expo if that makes a difference

**Comment by jgo80** [comment]
@prateem use this instead:
```
if (typeof window !== 'undefined') {
  window._frameTimestamp = null;
}
```

**Comment by GiladR1979** [comment]
What solved this for me is this, after tearing a few hairs for half a day:
`npm start -- --reset-cache`
or if you use yarn:
`yarn cache clean`

**Comment by Pramela-Devi-S** [comment]
Clean your cache use this command in your project directory->npx react-native clean cache. It should work
✔ Select all caches to clean › metro (Metro, haste-map caches), watchman (Stop Watchman and delete its cache)
✔ Clean Metro cache
✔ Clean Haste cache
✔ Clean React Native cache
✔ Stop Watchman
✔ Delete Watchman cache

**Comment by mehdiChibani** [comment]
> What solved this for me is this, after tearing a few hairs for half a day: `npm start -- --reset-cache` or if you use yarn: `yarn cache clean`

me too :)
