### ISSUE TITLE
AppClip shows TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions'

### ISSUE THREAD

**Issue by dawidzawada** [software-mansion/react-native-reanimated#3379]
## Description

Hi there! I'm working on an React Native App with smaller AppClip version. My component used at my "Full" app, is  importing these react-native-reanimated functions/objects:
`import Animated, { useSharedValue, useAnimatedStyle, useDerivedValue, withSpring, withTiming } from 'react-native-reanimated';`
and it is working fine, without any issues but the same component used at the same screen but in AppClip version cause these errors:
```
 ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native. 
```

I'm using manual linking(only for AppClip, full app have auto linking enabled) - in order to reduce & maintain AppClip size. Below I'm pasting my AppDelegate.h, AppDelegate.m and Podfile configuration, can you help me, and point where's the configuration issue with the AppClip project?
I'm using also the android "Instant App" on this project and there's also no issue.

## Snack or minimal code example

Podfile:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target '<APP-NAME>' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target '<APP-NAME>Tests' do
    inherit! :complete
    # Pods for testing
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    $RNMBGL.post_install(installer)
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

  end
end

target '<APP-NAME>Clip' do
  # The Pods which should be included in all projects
pod 'RNReanimated', :path => "../node_modules/react-native-reanimated"
pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
pod 'React', :path => "../node_modules/react-native/"
pod 'React-Core', :path => "../node_modules/react-native/"
pod 'React-CoreModules', :path => "../node_modules/react-native/React/CoreModules"
pod 'React-RCTActionSheet', :path => "../node_modules/react-native/Libraries/ActionSheetIOS"
pod 'React-RCTAnimation', :path => "../node_modules/react-native/Libraries/NativeAnimation"
pod 'React-RCTBlob', :path => "../node_modules/react-native/Libraries/Blob"
pod 'React-RCTImage', :path => "../node_modules/react-native/Libraries/Image"
pod 'React-RCTLinking', :path => "../node_modules/react-native/Libraries/LinkingIOS"
pod 'React-RCTNetwork', :path => "../node_modules/react-native/Libraries/Network"
pod 'React-RCTSettings', :path => "../node_modules/react-native/Libraries/Settings"
pod 'React-RCTText', :path => "../node_modules/react-native/Libraries/Text"
pod 'React-RCTVibration', :path => "../node_modules/react-native/Libraries/Vibration"
pod 'React-Core/RCTWebSocket', :path => "../node_modules/react-native/"
pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
# pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
# pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
# pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
# pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
pod 'react-native-webview', :path => "../node_modules/react-native-webview"
pod 'RNScreens', :path => "../node_modules/react-native-screens"
pod 'RNGestureHandler', :path => "../node_modules/react-native-gesture-handler"
pod 'react-native-safe-area-context', :path => "../node_modules/react-native-safe-area-context"
pod 'RNSVG', :path => "../node_modules/react-native-svg"

pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"

pod 'ReactCommon/turbomodule/samples', :path => '../node_modules/react-native/ReactCommon'

end
```

AppDelegate.m

```
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

@interface AppDelegate ()

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
[FIRApp configure];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"<APP-NAME>"
                                            initialProperties:nil];

  if (@available(iOS 13.0, *)) {
      rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
      rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.clip" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

#pragma mark - UISceneSession lifecycle

- (UISceneConfiguration *)application:(UIApplication *)application configurationForConnectingSceneSession:(UISceneSession *)connectingSceneSession options:(UISceneConnectionOptions *)options {
    // Called when a new scene session is being created.
    // Use this method to select a configuration to create the new scene with.
    return [[UISceneConfiguration alloc] initWithName:@"Default Configuration" sessionRole:connectingSceneSession.role];
}

- (void)application:(UIApplication *)application didDiscardSceneSessions:(NSSet<UISceneSession *> *)sceneSessions {
    // Called when the user discards a scene session.
    // If any sessions were discarded while the application was not running, this will be called shortly after application:didFinishLaunchingWithOptions.
    // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
}

@end
```
AppDelegate.h

```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;

@end
```

I can also provide my "Full" app configuration or some other files.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    "0.66.4"     |
| react-native-reanimated              |    "^2.4.1"     |
| NodeJS                               |     v14.19.3    |
| Xcode                                |     13.3.1     |

## Affected platforms

- [ ] Android
- [x] iOS - Only the AppClip version!
- [ ] Web

![Simulator Screen Shot - iPhone 12 - 2022-07-12 at 13 22 55](https://user-images.githubusercontent.com/16326546/178480430-90e087fd-f0a5-48d4-b0cb-b67b6df61b5d.png)

**Comment by whatdtech** [comment]
Having same issue with RN 0.68.2 and here is my package file

```
dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.7",
    "@react-native-community/datetimepicker": "^6.2.0",
    "@react-native-picker/picker": "^2.4.2",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@react-navigation/stack": "^6.2.2",
    "add": "^2.0.6",
    "axios": "^0.27.2",
    "expo": "^45.0.0",
    "expo-linear-gradient": "^11.3.0",
    "expo-local-authentication": "^12.2.0",
    "expo-navigation-bar": "^1.2.0",
    "expo-network": "^4.2.0",
    "lodash.values": "^4.3.0",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-animatable": "^1.3.3",
    "react-native-awesome-alerts": "^2.0.0",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^2.9.1",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-sensitive-info": "^5.5.8",
    "react-native-toast-message": "^2.1.5",
    "react-native-vector-icons": "^9.2.0",
    "rn-segmented-control": "^1.1.2",
    "uuid": "^8.3.2",
    "yarn": "^1.22.19"
  },
``
![error](https://user-images.githubusercontent.com/71651525/178793146-7f09b3e3-1329-41a5-987c-83feae1df353.png)
`

**Comment by whatdtech** [comment]
these are the errors 
**ERROR  TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.**

**Comment by NJHu** [comment]
ERROR  Error: Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by AlessandroGenerale17** [comment]
I have also been getting the same error on iOS for a quite a while now. I am left to think that there is a mistake in our AppDelegate file. I have been following all the posts about it and tried all suggested solutions mentioned in the comment but it still persists. Whenever I add it to a fresh project I have no issue using reanimated. The installation steps are a few and simple.

**Comment by regalstreak** [comment]
Some people managed to get it solved by doing [this](https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735456092). Can vouch for this solution as we're also not initializing the bridge in AppDelegate properly.

Downgraded to `v2.2.4` as a temporary workaround

**Comment by tomekzaw** [comment]
Hello @dawidzawada, thanks for reporting the problem.

Can you please check and let us know if https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735456092 resolves your issue?

**Comment by alexg-93** [comment]
anyone managed to make it work?
still getting the error **TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions']**

on android works fine .. only IOS getting this error

react-native version 0.66
tried all react-native-reanimated 2.x - 3.x versions same error ..

help please!

**Comment by dawidzawada** [comment]
> Hello @dawidzawada, thanks for reporting the problem.
> 
> Can you please check and let us know if [#1439 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735456092) resolves your issue?

I've solve this issue by using React Native's Animation API, but my AppClip code is not using separated class for initialising Bridge so that might be a solution.

**Comment by tomekzaw** [comment]
Thanks @dawidzawada for the response!

I will close the issue now since it only affects brownfield apps with custom setup.

If you encounter this problem, first please check if the solution from https://github.com/software-mansion/react-native-reanimated/issues/1439#issuecomment-735456092 works for you.

Otherwise, feel free to re-open the issue.
