### ISSUE TITLE
Android Build failed Task :react-native-reanimated:downloadBoost FAILED

### ISSUE THREAD

**Issue by pankajnegi1893** [software-mansion/react-native-reanimated#3625]
### Description

After Adding react-native-reanimated library in React Native 0.70.0 we are getting below issue in Window 10:

```
error Failed to launch emulator. Reason: Emulator exited before boot..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon, 3 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :react-native-reanimated
Native libs debug enabled: false
Android gradle plugin: 7.2.1
Gradle: 7.5.1
building Reanimated2
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :react-native-reanimated:downloadHermes UP-TO-DATE
Download https://github.com/facebook/hermes/tarball/hermes-2022-08-16-RNv0.70.0-716d48baf36b0b326ab82f53207b8682c87fc017

> Task :react-native-reanimated:downloadDoubleConversion UP-TO-DATE
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-reanimated:downloadBoost
Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

> Task :react-native-reanimated:downloadFolly UP-TO-DATE
Download https://github.com/facebook/folly/archive/v2021.07.22.00.tar.gz

> Task :react-native-reanimated:downloadGlog UP-TO-DATE
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-reanimated:downloadBoost FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
376 actionable tasks: 4 executed, 372 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.        
-----------
* What went wrong:
Execution failed for task ':react-native-reanimated:downloadBoost'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > java.net.SocketException: Connection reset

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 59s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-reanimated:downloadBoost'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > java.net.SocketException: Connection reset

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 59s

    at makeError (E:\SHWP\shwa-mobile\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at E:\SHWP\shwa-mobile\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (E:\SHWP\shwa-mobile\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (E:\SHWP\shwa-mobile\node_mo
`
```

I am struggling with the issue from past 2 days. Still not able to find the any solution.  I have tried with cache clean. Invalidated Cache and Restart in Android Studio but still we are facing above see. Please check the screenshot for more details:

![image_2022_09_29T11_55_37_507Z](https://user-images.githubusercontent.com/49673803/193197475-07f2a7bf-ffa8-49ec-8824-51ecde0afca8.png)

See OS configuration:

![image_2022_09_30T05_11_24_794Z](https://user-images.githubusercontent.com/49673803/193197531-cedf7edc-69f6-499d-9801-78945fb8d65e.png)

Thanks

### Steps to reproduce

 1. add below library in the project
 2. npm install @react-navigation/drawer
 3. npm install react-native-gesture-handler react-native-reanimated
 

### Snack or a link to a repository

https://github.com/react-navigation/react-navigation

### Reanimated version

2.10.0

### React Native version

0.70.0

### Platforms

Android

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey, `java.net.SocketException: Connection reset` suggests that there is some kind of connection problem when downloading Boost from server. Please try building the project again.

Also, this issue is specific to Reanimated 2.10. In a general case, Reanimated v2 should not download binaries from network. We plan to release 2.11 next week which should also resolve this problem.

**Comment by fkazemi5236** [comment]
I have the same problem
I cant build the app with any network connection
every time in every build, when the terminal arrived in task: react-native-reanimated:downloadBoost its stopped and exited from the terminal

@tomekzaw 

it seems this problem was happen in last 10 days :( because I could run my react-native app from 2weeks ago

**Comment by pankajnegi1893** [comment]
> Hey, `java.net.SocketException: Connection reset` suggests that there is some kind of connection problem when downloading Boost from server. Please try building the project again.
> 
> Also, this issue is specific to Reanimated 2.10. In a general case, Reanimated v2 should not download binaries from network. We plan to release 2.11 next week which should also resolve this problem.

@tomekzaw still library not updated. we are struggling with this issue. we are not able to run the application.

**Comment by tomekzaw** [comment]
@fkazemi5236 @pankajnegi1893 You know you can still use 2.9.1, right? You can also upgrade to 3.0.0-rc.3 if you don't use Reanimated 1 API.

**Comment by fkazemi5236** [comment]
so we should install "yarn add react-native-reanimated@3.0.0-rc.3"?
like this?

**Comment by tomekzaw** [comment]
Yes.

**Comment by tomekzaw** [comment]
@fkazemi5236 @pankajnegi1893 We have just published 2.11.0: https://www.npmjs.com/package/react-native-reanimated/v/2.11.0

**Comment by fkazemi5236** [comment]
this version needs to update Gradlew but I have some packages that not ok with this update

**Comment by fkazemi5236** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-reanimated:classpath'.
      > Could not find com.android.tools.build:gradle:7.3.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
        Required by:
            project :react-native-reanimated

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-reanimated:classpath'.
      > Could not find com.android.tools.build:gradle:7.3.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
          - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom
        Required by:
            project :react-native-reanimated

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (D:\diet_mobile_app\node_modules\execa\index.js:174:9)
    at D:\diet_mobile_app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\diet_mobile_app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\diet_mobile_app\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tomekzaw** [comment]
^ moved to #3680, closing this issue as 2.11.0 no longer downloads Boost.

**Comment by fkazemi5236** [comment]
thanks a lot @tomekzaw 
my problem was solved 😎

**Comment by mavine4512** [comment]
### **This is how I solve it**
RN 0.70.0
Previously i was using "react-native-reanimated": " 3.0.0",
each and every time when I want to build my RN app it took like 4hrs then failed  issue of network.

**_The solution for me was to lower it to :_** 
"react-native-reanimated": "2.11.0",

**Comment by urtheone** [comment]
RN 0.70.0 still happen！！！
Previously i was using "react-native-reanimated": " 3.0.0",
each and every time when I want to build my RN app it took like 4hrs then failed issue of network.

**Comment by amm834** [comment]
It's happening again in `react-native-reanimated` version `3.0.2`.

Build errors are at follow:

```

info Opening the app on Android...
info JS server already running.
info Launching emulator...
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.3.1
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/android/local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/android/local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/execa/index.js:174:9)
    at /Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
q
:
q

✨  Done in 30.38s.
➜  mobile git:(main) ✗
➜  mobile git:(main) ✗
➜  mobile git:(main) ✗
➜  mobile git:(main) ✗ nvim package.json
➜  mobile git:(main) ✗



```

**Comment by yujunfan** [comment]
它在react-native-reanimated版本中再次发生3.1.0。

构建错误如下：


info Opening the app on Android...
info JS server already running.
info Launching emulator...
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.3.1
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/android/local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/android/local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/execa/index.js:174:9)
    at /Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/macbook/myanmar-cyber-youths/alpha-learn/apps/mobile/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
q
:
q

✨  Done in 30.38s.
➜  mobile git:(main) ✗
➜  mobile git:(main) ✗
➜  mobile git:(main) ✗
➜  mobile git:(main) ✗ nvim package.json
➜  mobile git:(main) ✗

**Comment by ali-wesdigital** [comment]
This is happening for latest version 3.1.0 as well. Is there a fix?

**Comment by piaskowyk** [comment]
@ali-wesdigital Which React Native version do you use? Do you want to build it on Windows or MacOS?

**Comment by luojiong** [comment]
Has anyone solved this problem yet ？  "react-native-reanimated": "^2.9.1",  "react-native": "0.64.0",  There is still this problem

**Comment by piaskowyk** [comment]
@luojiong Could you provide me a reproduction? I am not able to reproduce this issue on my current setup.

**Comment by luojiong** [comment]
@piaskowyk  Recently, my work has been in a hurry and I don't have time. I will provide it in a while  thanks

**Comment by amm834** [comment]
It's happening on my Mac too what op do you use?

**Comment by yxwandroid** [comment]
不能把 boost 放在本地进行引用吗

**Comment by chamaldesilva** [comment]
> ### **This is how I solve it**
> RN 0.70.0 Previously i was using "react-native-reanimated": " 3.0.0", each and every time when I want to build my RN app it took like 4hrs then failed issue of network.
> 
> **_The solution for me was to lower it to_** "react-native-reanimated": "2.11.0",

This works for me! Thanks.

**Comment by renatomserra** [comment]
having the same issue with 3.4.2 :( anyone found a solution?

**Comment by eisodev** [comment]
> 
Im getting this on 3.4.2, think I must revert to 2.17.0 again.
```
> Task :react-native-reanimated:downloadFolly FAILED
546 actionable tasks: 6 executed, 540 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:downloadFolly'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ConnectTimeoutException: Connect to https://github.com:443 [github.com/140.82.121.4] failed: connect timed out
```

**Comment by chuangdev** [comment]
Check your local hosts file for any configurations related to GitHub's domain, and check your VPN available.

I solved the problem by removing the GitHub host from the host file
