### ISSUE TITLE
cannot read properties of undefined (reading 'configurelayoutanimation') on ios while debugging in chrome

### ISSUE THREAD

**Issue by WillyRamirez** [software-mansion/react-native-reanimated#3964]
### Description

I receive the above error when trying to apply layout animations on ios. Occurs on both simulators and real devices.

` <Animated.View
      style={styles.container}
      entering={SlideInDown}
      exiting={SlideOutUp}
    >`

Please note that this issue will not occur on the provided snack itself since debug mode cannot be turned on. Please run on a device

### Steps to reproduce

1. apply [patch](https://github.com/software-mansion/react-native-reanimated/issues/3951) to get around broken debug errors
2. start "debugging in chrome" 
3. go to the screen where a layout animation is applied to an animated component
4. you'll see the above error

### Snack or a link to a repository

https://snack.expo.dev/VD1QY1Q-q

### Reanimated version

3.0.0-rc.10

### React Native version

0.69.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iphone 11, simulator iphone 13 ios 15.2

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Thanks @WillyRamirez for reporting this issue! Should be fixed with #4289.

**Comment by Ritesh-Kumar-4946** [comment]
still facing the same issue with v3.1.0
`Failed to print error:  undefined has no properties`
any luck with new version or we need to downgrade the version

Thanks
