### ISSUE TITLE
[V3] Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method

### ISSUE THREAD

**Issue by arasrezaei** [software-mansion/react-native-reanimated#4135]
### Description

Hi there, just a clean build to test v3,
my code:
```
import Animated from 'react-native-reanimated';

const App = () => {
  return (
    <Animated.View style={{width: 200, height: 200, backgroundColor: 'red'}} />
  );
};

export default App;
```
got this error:
`Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method "Lcom/swmansion/reanimated/NativeProxy;.registerEventHandler(Lcom/swmansion/reanimated/nativeProxy/EventHandler;)V", js engine: hermes`

package.json:
```
 "dependencies": {
    "@shopify/react-native-skia": "^0.1.175",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "^3.0.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0"
  },
```

### Steps to reproduce

 just did a clean build with that packages.

### Snack or a link to a repository

simple code, no need to repository

### Reanimated version

3.0.0

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by asfaqehussain** [comment]
I'm also facing the same issue 
React native version 69.5
Reanimated version 3.0.0

**Comment by vanenshi** [comment]
Also facing the same issue here

**Comment by dpk-developer** [comment]
Just downgrade your react-native-reanimated from v3 to v2

**Comment by jet2018** [comment]
Was there any work-around on this issue?

**Comment by n-ii-ma** [comment]
Also getting this error on Android 8.

No issue on Android 13

**Comment by mysport12** [comment]
Firebase crash stats indicate this is affecting both Android 7 and Android 8 users

**Comment by efstathiosntonas** [comment]
@mysport12 same here, affecting ~50 users that use old devices.

**Comment by efstathiosntonas** [comment]
@tomekzaw sorry for being an ass, any idea what might causing this?

**Comment by kekami** [comment]
Could it potentially be fixed with the rework in https://github.com/software-mansion/react-native-reanimated/pull/4116 ?

**Comment by efstathiosntonas** [comment]
@kekami don't know if the PR is finished or not, I've patched the changes from that PR and the problem is still there. I've used an Android 8 emulator.

**Comment by efstathiosntonas** [comment]
@balmasich it works as a charm. I'm wondering though if changing methods from `private` to `public` affects something else. Will keep testing. Thank you!

**Comment by hassancodess** [comment]
@balmasich it works 💯
Thanks!

**Comment by dziekonskik** [comment]
Hi, how do I use this patch? I have this same issue on android v8 react "react-native": "0.71.4",  "react-native-reanimated": "^3.0.2",

**Comment by hassancodess** [comment]
@dziekonskik you just have to open this file located at this given path and change the access modifiers from private to public as shown in the patch
 node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java

**Comment by dziekonskik** [comment]
works great! thank you @hassancodess :)

**Comment by wcastand** [comment]
Hi, how does the release process work? The repo made a new patch 3.0.2 "just" to fix the typings but is not publishing a new patch once they merged a Pr that avoid a crash on Android 7/8 that prevent most people to use v3.

How do you decide when to update/patch or not or is there a release plan somewhere?

**Comment by panoramix360** [comment]
The problem still persists, the fix is already launched on 3.0.2?

**Comment by yepMad** [comment]
That is not in v3.0.2. Do we have any forecast for the release of a new patch?

**Comment by nonam4** [comment]
same problem here, waiting for a official fixed release

**Comment by maksimgorodilov** [comment]
Also waiting for the release

**Comment by yepMad** [comment]
This patch is already in the main, there just isn't a release yet. It's not 100% recommended, but it solves crashes in production. You can run `yarn add https://github.com/software-mansion/react-native-reanimated`

My Crashlytics stopped screaming with this solution.

**Comment by Rag0n** [comment]
It would be nice to release new reanimated version, there's also another android [issue](https://github.com/software-mansion/react-native-reanimated/issues/3879) and so we've to use 2 patches already.

**Comment by piaskowyk** [comment]
Reanimated 2.15.0 contains all those fixes, and Reanimated 3.1.0 will be released soon.

**Comment by samitha9125** [comment]
@tomekzaw i know it is really hard to manage such a complicated package. But we would really like to know that when can we expect the 3.1.0 release?

**Comment by tomekzaw** [comment]
Hey @samitha9125, we are still waiting for some fixes before we can release 3.1.0, but in the meantime you can use nightly builds from here: https://github.com/software-mansion/react-native-reanimated/actions/workflows/build-nightly-npm-package.yml

**Comment by efstathiosntonas** [comment]
@tomekzaw how to install the night build? 

yarn add url_of_the_artifaft zipped file?

**Comment by meabed** [comment]
This is fixed in the latest nightly build https://github.com/software-mansion/react-native-reanimated.git#66dc04934a7b76076bce78f5bf5c303210f0e5ab

**Comment by tomekzaw** [comment]
@efstathiosntonas Reanimated nightly builds are published as GitHub Actions artifacts. In order to use them in your app, you will need to:
1. Download v3 nightly zip archive from https://github.com/software-mansion/react-native-reanimated/actions/workflows/build-nightly-npm-package.yml
2. Unzip the archive from the command line with `unzip react-native-reanimated-3.0.2.tgz`
3. Add a dependency with `yarn add file:/path/to/the/react-native-reanimated-3.0.2.tgz`

**Comment by tonyhohf** [comment]
I am facing the same problem.
Anyone knows how to downgrade from react-native-reanimated V3 to V2?
Thanks

**Comment by tonyhohf** [comment]
i am facing this error when trying to use Drawer Navigation.

**Comment by asfaqehussain** [comment]
@tonyhohf 
To downgrade just install like this 
Yarn add react-native-reanimated@versionyouneed

Eg -react-native-reanimated@2.0

**Comment by tonyhohf** [comment]
Noted with thanks. 

Sent from Yahoo Mail on Android 
 
  On Sun, 16 Apr 2023 at 19:52, Asfaqe ***@***.***> wrote:   


@tonyhohf
To downgrade just install like this
Yarn add ***@***.***

Eg ***@***.***

**Comment by tonyhohf** [comment]
Noted with thanks

**Comment by josegiufrida** [comment]
I tested the latest version `3.1.0` and can confirm that it resolves the error

**Comment by tonyhohf** [comment]
Dear Sir,
I have encountered the problem as follow after installing the react-native-reanimated version 3.1.0 :-


Anyone can help?
ThanksRegardsTony Ho

    On Thursday, 27 April 2023 at 22:16:39 GMT+8, Jose ***@***.***> wrote:  
 
 


I tested the latest version 3.1.0 and can confirm that it resolves the error

**Comment by claudiozam** [comment]
Hi @tonyhohf, try to clean the android / ios project.

https://github.com/pmadruga/react-native-clean-project#readme

I tested the latest version 3.1.0 and can confirm that it resolves the error on production.

**Comment by tonyhohf** [comment]
Dear sir, Thanks. Will try to clean my android project. 
Regards Tony Ho 

Sent from Yahoo Mail on Android 
 
  On Mon, 1 May 2023 at 23:58, claudio ***@***.***> wrote:   


Hi @tonyhohf, try to clean the android / ios project.

https://github.com/pmadruga/react-native-clean-project#readme

I tested the latest version 3.1.0 and can confirm that it resolves the error on production.

**Comment by tonyhohf** [comment]
Dear Sir,
After installing react-native-reanimated v3.1.0 and did clean the project,  I encounter the problem as follow:
-> No AAF for react-native-reanimated found.
but the build of the project is successful.
note: if I install version 2.15.0 or 2.17.0,  AAF for react-native-reanimated is found.
Hopefully anyone can help.
thanksRegardsTony Ho





    On Monday, 1 May 2023 at 23:58:12 GMT+8, claudio zamoszczyk ***@***.***> wrote:  
 
 


Hi @tonyhohf, try to clean the android / ios project.

https://github.com/pmadruga/react-native-clean-project#readme

I tested the latest version 3.1.0 and can confirm that it resolves the error on production.

**Comment by AlgoAngel** [comment]
there is the way to fix it?
