### ISSUE TITLE
useAnimatedKeyboard returns wrong height after opening a modal while keyboard is open

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#4351]
### Description

While working on KeyboardAvoidingView PR https://github.com/software-mansion/react-native-reanimated/pull/4339 I discovered that `useAnimatedKeyboard` on iOS might return a `height` for the keyboard with 1 frame delay and returns a wrong result:

```js
{
  state: 4, // closed
  height: 318
}
```

It happens when you open a modal with `animationType="none"` when the keyboard is visible. It replaces the keyboard with the modal in a single frame. But the heigh of the keyboard has a frame delay.

### Steps to reproduce

1. Focus input to open a keyboard
2. Open modal with `animationType="none"`

You can use this branch for reproducing:
https://github.com/software-mansion/react-native-reanimated/pull/4339

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/pull/4339

### Reanimated version

3.0.2

### React Native version

0.71

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by terrysahaidak** [comment]
This PR has a KeybobardAvoidingView example that reproduces the example:
https://github.com/software-mansion/react-native-reanimated/pull/4339

**Comment by tomekzaw** [comment]
Should be fixed with #4360.

**Comment by terrysahaidak** [comment]
After testing #4339 with the latest code, it looks like it's not completely fixed, here you can see that it for a frame uses the wrong height, but also logs a different height value, seems like it's the height without word suggestions

It's random, you can reproduce it by clicking it for 10-20 times

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/7809008/233733977-da0f1833-99d9-43e5-bf12-d4f664dae612.png">

**Comment by azcarraga** [comment]
@terrysahaidak - not sure if it's related, but i'm seeing a frame delay on a simple animation that tracks the keyboard height:

https://github.com/software-mansion/react-native-reanimated/issues/4431
