### ISSUE TITLE
withRepeat breaks reanimated after some time on Android

### ISSUE THREAD

**Issue by azhavrid** [software-mansion/react-native-reanimated#4387]
### Description

Idle `withRepeat` animation breaks all reanimated animations after ~12 mins on Android emulator/device.

Attaching sample code to reproduce

### Code to reproduce

```jsx
import React, { useEffect } from 'react';
import { View } from 'react-native';
import Animated, { useAnimatedStyle, useSharedValue, withRepeat, withTiming } from 'react-native-reanimated';

const App = () => {
  const sharedValue = useSharedValue(1);

  useEffect(() => {
    sharedValue.value = withRepeat(withTiming(2, { duration: 1000 }), -1, true);
  }, [sharedValue]);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      backgroundColor: 'red',
      width: 100,
      height: 100,
      marginTop: 100,
      alignSelf: 'center',
      transform: [{ scale: sharedValue.value }],
    };
  });

  return (
    <View>
      <Animated.View style={animatedStyle} />
    </View>
  );
};

export default App;

```

### Notes

- The number of views animated using ﻿`animatedStyle` does not decrease the “break time” duration. 
- Increasing the number of shared values variables appears to reduce the “break time” proportionally. In my tests, using `﻿withRepeat` for 10 shared values caused the animation to break after approximately 1 minute and 30 seconds.
- on iOS everything works fine

### Steps to reproduce

1. Launch app on android emulator/device
2. Wait for ~12 minutes

### Reanimated version

3.1.0 (3.0.2 had this issue as well)

### React Native version

0.71.6

### Platforms

Android

**Comment by psychopathh** [comment]
I have the same thing happening on version 2.14.0, after about 12-15 minutes the application just crashes only on android with an error in java eofexception null.

**Comment by tironiigor** [comment]
I'm not sure if it's related to #4419, but I'm also experiencing issues with the animation getting stuck. On Android testing with a Samsung S20 after leaving the animation playing for some time it just stops working and all animations after that just don't play.

**Comment by paperrin** [comment]
Ok, only found this issue now, but seems to be very similar if not identical issue to what we're experiencing : #4513 
In our case, we tested on multiple react-native versions, and v2 and v3 of reanimated are affected.
It's also reproducible on both iOS and Android, and on emulators and diverse real devices (100%).

I also provided a github repo to reproduce.

**Comment by piaskowyk** [comment]
Resolved in: https://github.com/software-mansion/react-native-reanimated/pull/4579. The fix will be available in the next release.

**Comment by efenstakes** [comment]
> #4579

This seems to still be happening in 2024. On both android and iOS devices, we did not test on simulators but on a couple of devices, the issue persists.
