### ISSUE TITLE
Typescript transpiling issue

### ISSUE THREAD

**Issue by yurykorzun** [software-mansion/react-native-reanimated#4828]
### Description

After upgrading to the most recent version of react-native and reanimated, I couldn't run the app because the bundled JS has a syntax error. RN throws an error "Compiling JS failed. Invalid Expression".
After looking the JS bundle, I found that this code was incorrectly compiled:

src/reanimated2/threads.ts

`return (...args) => runOnJS(runWorkletOnJS<A, R>)(fun, ...args);`

was compiled to:

`return runOnJS(runWorkletOnJS<A, R>).apply(void 0, [fun].concat(args));`

If I understand correctly, generic types should be erased, but they weren't.

What could be causing it? I can patch the code in node_modules and remove generic types, but it's not an acceptable solution.

### Steps to reproduce

1. Upgrade RN and Reanimated to 0.72 and 3.4.0
2. Run the app

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.4.0

### React Native version

0.72

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by hirbod** [comment]
Maybe related: we get this error.

![simulator_screenshot_1665253D-587D-48D0-8E0E-86432D6EEE38](https://github.com/software-mansion/react-native-reanimated/assets/504909/6929c840-952d-4201-9799-8f384ec28436)

**Comment by tjzel** [comment]
Hi, as you can see from [npm code section](https://www.npmjs.com/package/react-native-reanimated/v/3.4.0?activeTab=code):

![Screenshot 2023-07-26 at 19 41 04](https://github.com/software-mansion/react-native-reanimated/assets/40713406/bbcf86e6-524a-4266-9344-17862fe415dd)

TS source is compiled properly to ESModule. 

I can guess from what the issue stems - we changed our package structure so `/lib` is a bit different. Maybe for some reason Node looks for ESModule files in `/src` directory and is confused there by TS files - due to old `yarn.lock` which somehow got corrupted and doesn't regenerate properly.

And I think @hirbod it's totally related!

**Comment by MattReimer** [comment]
I can't tell if this is related or not but we get a problem that feels similar: 

```
Exporting with Webpack...
Failed to compile
CommandError: /Users/**********/Work/Git/somerepo/node_modules/react-native-reanimated/lib/module/reanimated2/animation/util.js 1:13149
Module parse failed: Unexpected token (1:13149)
File was processed with these loaders:
 * ../../node_modules/@expo/webpack-config/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
```

This happens when upgrading to `3.4.1`. Dripping back to `3.3.0` fixes the issue.

I'm not really a front-end developer so I don't understand webpack config. This is coming from our CI when building and deploying a bigger project

I'll include the `babel.config.js` from our Expo build in case it helps.  The following works fine for `3.3.0` but not `3.4.1`

```js
module.exports = function (api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      'react-native-reanimated/plugin', // reanimated must be last: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation
    ],
  }
}

```

**Comment by tjzel** [comment]
Hi @MattReimer, it should be fixed with #4838, we will make a patch 3.4.2 soon with it.

**Comment by Latropos** [comment]
Closing since fix: https://github.com/software-mansion/react-native-reanimated/pull/4838 is already merged (but not released yet)

**Comment by laurens-lamberts** [comment]
I'm still experiencing this with reanimated 3.4.2.
Rolling back to 3.3.0 resolves the issue for me.

Please let me know if I can support on testing a potential new fix.

**Comment by tjzel** [comment]
@laurens-lamberts This is not an issue that comes from us - there's some problem when upgrading Reanimated regarded with your package manager's cache. Try removing your `node_modules`, removing your `yarn.lock` or `package-lock.json` and clearing your package manager cache `yarn cache clean` or `npm cache clean`.

**Comment by markoj3s** [comment]
It would be nice to know the root cause of this transpiling issue. I am not very satisfied to rely on the magic of regenerating the `yarn.lock` file.

**Comment by markoj3s** [comment]
I was personally getting either

> Maybe related: we get this error.
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/504909/256302888-6929c840-952d-4201-9799-8f384ec28436.png">
> EDIT: After following [this advice](https://github.com/software-mansion/react-native-reanimated/issues/4645#issuecomment-1651399197) (deleting yarn.lock), the issue went away.

or



> ### Description
> After upgrading to the most recent version of react-native and reanimated, I couldn't run the app because the bundled JS has a syntax error. RN throws an error "Compiling JS failed. Invalid Expression". After looking the JS bundle, I found that this code was incorrectly compiled:
> 
> src/reanimated2/threads.ts
> 
> `return (...args) => runOnJS(runWorkletOnJS<A, R>)(fun, ...args);`
> 
> was compiled to:
> 
> `return runOnJS(runWorkletOnJS<A, R>).apply(void 0, [fun].concat(args));`
> 
> If I understand correctly, generic types should be erased, but they weren't.
> 
> What could be causing it? I can patch the code in node_modules and remove generic types, but it's not an acceptable solution.
> 
> ### Steps to reproduce
> 1. Upgrade RN and Reanimated to 0.72 and 3.4.0
> 2. Run the app
> 
> ### Snack or a link to a repository
> https://github.com/software-mansion/react-native-reanimated
> 
> ### Reanimated version
> 3.4.0
> 
> ### React Native version
> 0.72
> 
> ### Platforms
> Android, iOS
> 
> ### JavaScript runtime
> None
> 
> ### Workflow
> None
> 
> ### Architecture
> None
> 
> ### Build type
> None
> 
> ### Device
> None
> 
> ### Device model
> _No response_
> 
> ### Acknowledgements
> Yes

Regenerating the `yarn.lock` and cleaning all the caches does work indeed, but it forces me to upgrade all packages even those I don't want to.

**Comment by markoj3s** [comment]
I am also getting 

> Maybe related: we get this error.
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/504909/256302888-6929c840-952d-4201-9799-8f384ec28436.png">
> EDIT: After following [this advice](https://github.com/software-mansion/react-native-reanimated/issues/4645#issuecomment-1651399197) (deleting yarn.lock), the issue went away.

this error. I am wondering why uninstalling then re-installing react-native-reanimated + clearing cache does not solve this issue? Deleting `yarn.lock`, `node_modules` and clearing `yarn cache` does indeed solve the issue, but would be nice to know the root cause and how to precisely fix the issue. I am not much comfortable with simply deleting and regenerating the `yarn.lock`.

**Comment by tjzel** [comment]
Unfortunately this is kind-of irreproducible error, it happened only to a handful of users and is obviously related to the project and yarn/npm environments and configs.

From my own experience `yarn.lock` file - even though automatically managed - can get corrupted after some time (once I deleted all the `yarn.lock` files in our repo and regenerated them, because some of them got corrupted and were giving all kinds of funky, weird errors).

Luckily, `yarn.lock` file structure is pretty simple and after regenerating you can compare the key differences, see what has changed (unless you haven't upgraded your dependencies in a long time, etc. - then it's obviously going to be impossible).

I understand your reluctancy to regenerate the `yarn.lock` but it is the solution that works here.

**Comment by tomgreco** [comment]
Deleting yarn.lock and doing a clean install does not fix this for me.

**Comment by tjzel** [comment]
@tomgreco Try with this [comment](https://github.com/software-mansion/react-native-reanimated/issues/5112#issuecomment-1803524401), maybe it will work for you.

**Comment by DanielKuhn** [comment]
I still get this error - any help is highly appreciated
https://github.com/software-mansion/react-native-reanimated/issues/5789
