### ISSUE TITLE
"Cannot read property 'CLAMP' of undefined" in version 3.5.3

### ISSUE THREAD

**Issue by mlazari** [software-mansion/react-native-reanimated#5109]
### Description

After updating react-native-reanimated from `3.5.2` to `3.5.3` the "Extrapolation" export seems to be undefined, Extrapolation.CLAMP throws a "Cannot read property 'CLAMP' of undefined" error.

Seems to be caused by this change: https://github.com/software-mansion/react-native-reanimated/compare/3.5.2...3.5.3#diff-0974724d9e373bbe0c20e339120d6d09499ab9b93e14d6d0f9e68076492f37ecR63

### Steps to reproduce

```
import { Extrapolation } from 'react-native-reanimated';

// ...
// Use Extrapolation.CLAMP
// ...
```

### Snack or a link to a repository

https://github.com/mlazari/ReanimatedRepro2

### Reanimated version

3.5.3

### React Native version

0.72.4

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Samsung Galaxy A52 (Android 13), iPhone SE 2020 (iOS 16.6.1)

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Fixed in [`3.5.4`](https://www.npmjs.com/package/react-native-reanimated/v/3.5.4) :)

**Comment by mlazari** [comment]
Thank you!

**Comment by mlazari** [comment]
@tjzel  Hmm, actually I put 3.5.4 in my repro repository and still see the error. Let me double check.

**Comment by tjzel** [comment]
If you use VSCode, sometimes it's required to reload it in order for TS Server to reload the files.

**Comment by mlazari** [comment]
@tjzel Yes, looks like it was a caching issue. Looks good now. Thank you!
