### ISSUE TITLE
Unable to complete release build for iOS

### ISSUE THREAD

**Issue by glopez-askit** [software-mansion/react-native-reanimated#5460]
### Description

I want to test the release build of my application, and I'm encountering the following error:

```
**BUILD FAILED**

The following build commands failed:
CompileC /Users/gianllopez/Library/Developer/Xcode/DerivedData/<project>/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/ReanimatedRuntime.o /<project>/app/node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/ReanimatedRuntime.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods')
(1 failure)
```

I've been dealing with this issue for several days, and I need to know how to resolve it. I've tried resetting the cache for all project components. The strange thing is that the release build for Android works fine, but for iOS, the same error persists. I've attempted deleting the simulator and testing on different models, but the issue persists.

Additionally, it's worth noting that the application functions perfectly at all times, and the issue only arises when generating the release build.

I'm currently working in a **Mac Mini M2** with the **MacOS 14.1.2**.

### Steps to reproduce

.

### Snack or a link to a repository

.

### Reanimated version

3.5.4

### React Native version

0.70.10

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

iOS simulator

### Device model

iPhone 15 Pro Max

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Fixed in https://github.com/mrousavy/react-native-vision-camera/pull/2270, update RNVisionCamera to 2.16.6.

**Comment by HugoGresse** [comment]
Hey there, I'm having the same issue, exact same log, updating react-native-vision-camera did not fix the issue 

        "react-native-reanimated": "^3.6.1",
        "react-native-vision-camera": "^2.16.6",
        
 through xcode, I'm having the same issue as #5446
