### ISSUE TITLE
Jest test fails when trying to mock reanimated

### ISSUE THREAD

**Issue by davidskaarup** [software-mansion/react-native-reanimated#582]
I mock reanimated in my snapshot test as described in the documentation:

`jest.mock("react-native-reanimated", () => require("react-native-reanimated/mock"))`

But my test fails with the following error:

```
/[...]/node_modules/react-native-reanimated/mock.js:30
      " __value": number;
                ^

    SyntaxError: Unexpected token :
```

What am I doing wrong?

**Comment by radko93** [comment]
I can confirm that this got broken after 1.4 (rolling back helps).

**Comment by radko93** [comment]
This is the pr that added this #522. Maybe we're missing babel config?

**Comment by jakub-gonet** [comment]
This happens because there are TS annotations in `.js` file. I created #613 which should fix that

**Comment by ShawnCholeva** [comment]
@jakub-gonet I noticed this got merged to master and I currently have 1.7.0 pulled down am still seeing the same issue.  This picture if from` \node_modules\react-native-reanimated`.  Could this have changed? 

![image](https://user-images.githubusercontent.com/13332685/76347137-1b5eae00-62d4-11ea-97c9-0b0b38d7af68.png)

**Comment by jakub-gonet** [comment]
It should be released on 1.7.1, try checking that
