### ISSUE TITLE
Can't animate boxShadow in RN 0.76+

### ISSUE THREAD

**Issue by C0rren** [software-mansion/react-native-reanimated#6687]
### Description

useAnimatedStyle does not seem to support boxShadow animations - a new feature in React Native 0.76+. When trying to animate box shadows, the shadows disappear as soon as any animation code runs in the hook.

Please note that my repro is very simple but there are many ways to make this bug happen. For example, you can literally run any reanimated interpolator that affects the shadow and the shadow will immediately disappear, you don't even need to return and use a value for the shadow.

### Steps to reproduce

1. Set up RN 0.76.1+ with react native reanimated
2. Create an animated Pressable component with createAnimatedComponent
3. create animated box shadow styles and do anything, maybe animate on click for example
4. shadow disappears when button is pressed instead of being animated - and never returns

### Snack or a link to a repository

https://github.com/C0rren/ReactNativeReanimatedIssue

### Reanimated version

3.16.1

### React Native version

0.76.1

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

Emulator (iPhone 16, iOS 18)

### Device model

Emulator (iPhone 16, iOS 18)

### Acknowledgements

Yes

**Comment by marcel-happyfloat** [comment]
Any news? Is this supported with reanimated 4 out of the box? Thank you 🚀

**Comment by patrycjakalinska** [comment]
hi @marcel-happyfloat, you can look at the related PR, as soon as it is merged it'll be included in next Reanimated version c:

**Comment by davor-bauk-sh** [comment]
Any chance of implementing this in Reanimated 3.16.x for folks using Expo 52?

**Comment by patrycjakalinska** [comment]
@davor-bauk-sh, it'll be included in 3.17.0, so as soon as it is out you can bump the Reanimated manually (using [development build](https://docs.expo.dev/develop/development-builds/introduction/)) c:

**Comment by MorganTrudeau** [comment]
This is crashing for my on react-native@0.78.0 on Android. Getting error:

```
Error while updating property 'boxShadow' of a view managed by: RCTView
```

I am animating the box shadow like so:

```

**Comment by patrycjakalinska** [comment]
hi @MorganTrudeau, can you provide me with a full snack? I've run this code fragment on Android and it worked for me c:

**Comment by bonnmh** [comment]
Hi team,

The previous boxShadow crash on Android is fixed, but it has been replaced by a severe performance issue. Scrolling through a <ScrollView /> containing multiple views with animated boxShadow causes significant JS and UI thread lag on Android. The issue occurs on both platforms, but the lag is significantly more severe on Android. On iOS, the lag is present but less pronounced.

The performance returns to normal immediately after removing the boxShadow property from the style object in useAnimatedStyle.

To Reproduce:
Render a list of components within a <ScrollView />. Each component must contain a view using useAnimatedStyle to apply a boxShadow. Scrolling the list on Android will cause noticeable stuttering and frame drops.

```
const animatedStyle = useAnimatedStyle(() => { 
  const shadow = pressed.value ? innerShadow : defaultShadow;

  return {
    backgroundColor: '...', 
    boxShadow: shadow,
  };
});
```

Environment:

**react-native**: 0.77.2
**react-native-reanimated**: 3.17.3 | 3.17.4 | 3.17.5 | 3.18.0
**OS**: Android/iOS
**Device Test**: iPhone 14 Pro Max, Samsung Galaxy A16 5G

**Comment by mfkrause** [comment]
@patrycjakalinska This is still crashing for us on Reanimated 3.17.5 and React Native 0.79.5, only on Android as well. iOS works fine.

Here's a reproducible snack. Crashes on the newest Expo Go version on Android: https://snack.expo.dev/@kuatsu_mkrause/spunky-violet-peanut

**Comment by patrycjakalinska** [comment]
hi @mfkrause, thanks for bringing this to our attention, for now until we find a solution you can use it by animating between two boxShadow objects:

``` tsx

import { useEffect } from 'react';
import { TouchableWithoutFeedback, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
  interpolateColor,
} from 'react-native-reanimated';

const SIZE = 100;
export default function EmptyExample() {
  const active = useSharedValue(false);

  const handlePress = () => {
    active.value = !active.value;
  };

  const shadowStyles = useAnimatedStyle(() => {
    const boxShadow1 = {
      offset: 0,
      offsetY: 24,
      blurRadius: 36,
      offsetX: 10,
      spreadDistance: 0,
      color: 'blue',
    };
    const boxShadow2 = {
      offsetX: 0,
      offsetY: 10,
      blurRadius: 10,
      spreadDistance: 0,
      color: 'purple',
    };
    return { boxShadow: [withTiming(active.value ? boxShadow2 : boxShadow1)] };
  });

  return (
    <SafeAreaView>
      <TouchableWithoutFeedback onPress={handlePress}>
        <Animated.View
          style={[
            { height: SIZE, width: SIZE, borderRadius: 10 },
            shadowStyles,
          ]}>
          <View
            style={{ width: SIZE, height: SIZE, backgroundColor: 'green' }}
          />
        </Animated.View>
      </TouchableWithoutFeedback>
    </SafeAreaView>
  );
}


```


https://github.com/user-attachments/assets/0097e69c-d832-457b-a0d9-4606671d2a55

**Comment by patrycjakalinska** [comment]
followup, I've opened a PR that will fix your issue https://github.com/software-mansion/react-native-reanimated/pull/8350 c:
