### ISSUE TITLE
flicker screen problem

### ISSUE THREAD

**Issue by wvq** [software-mansion/react-native-reanimated#7146]
### Description

I don't know why the screen keeps flickering. I tested several models of iPhone.

simplely `useSharedValue` and transform view's `translateY`, no matter using `timing` method or programmatically change the value,  I't flickering.

[reproduce-flickering-issue-repo](https://github.com/wvq/example-use-animated-keyboard.git)

https://github.com/user-attachments/assets/282579e4-b37d-4089-8aea-dd2a2c9dba95

### Steps to reproduce

1. npx create-expo-app@latest
2. add some screen
3. use react-native-reanimated at first page
4. second page flickering

### Snack or a link to a repository

https://github.com/wvq/example-use-animated-keyboard.git

### Reanimated version

3.17.1

### React Native version

0.77.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

iPhone X, iPhone 15

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
It looks like a long-known `react-native-screen` issue with the native stack header. Can you set `headerShown` to `false` on your navigator and see if the issue still persists?

like this:
```tsx
 <StackNavigator.Navigator
  screenOptions={{
    headerShown: false
  }}>
```

Let me know when you test it.

**Comment by wvq** [comment]
@MatiPl01  It's true, the screen stop flickering when `headerShow` is `false`.

**Comment by winhome-nitinkachhadiya** [comment]
is there any fix available where we can keep headerShow=true and still works?

**Comment by wvq** [comment]
@winhome-nitinkachhadiya Still doesn't work, I used a custom title instead. The native header not only flicking issue, but it also blocks the Android status bar internally, making it hard to control.

**Comment by MatiPl01** [comment]
> is there any fix available where we can keep headerShow=true and still works?

Which versions of `react-native`, `react-native-reanimated` and `react-native-screens` do you use? I couldn't reproduce this issue recently in the latest versions so I think it is gone but the problem was happening before in older versions.

> this also create issue on Pressable button in iPhonexs. [@MatiPl01](https://github.com/MatiPl01) [@wvq](https://github.com/wvq)

I think that the problem with pressable button is a separate thing. You may try using pressables from `react-native-gesture-handler` and check if they work.
